[
    {
        "category": "PROTECT",
        "classType": "JOB",
        "result.status": "FAILED",
        "result.error.code": "ABK0018",
        "result.error.detailedDescription": "The backup of this Kubernetes namespace was not successful because of a problem on the protection storage.",
        "result.error.extendedReason": "Unable to setup backup.  Unable to create directory 'Kubernetes_Backups_-_TEST_PLC-ppdm-01-a2e89/PLCTLP-694fb9a3-e763-4352-8b08-e0b323f863f0/Stagings/e6e4041f-3e15-47bf-b03c-9128d568a63c/demo-ns/1731594892413651527':  [5005] No space left on device",
        "result.error.reason": "Unable to back up namespace 'demo-ns' in Kubernetes cluster 'Cluster-01' because of a protection storage issue.",
        "result.error.remediation": "Verify that the PowerProtect DD System is fully functional and that the DD Boost ports are open between the Kubernetes cluster and the PowerProtect DD System.",
        "asset.name": "demo-ns",
        "asset.type": "KUBERNETES",
        "host.name": null,
        "host.type": null,
        "inventorySource.type": "KUBERNETES",
        "protectionPolicy.name": "Kubernetes Backups - TEST PLC",
        "protectionPolicy.type": "KUBERNETES",
        "createTime": "2024-11-14T14:34:02.518Z",
        "endTime": "2024-11-14T14:34:50.983Z"
    },
    {
        "category": "PROTECT",
        "classType": "JOB",
        "result.status": "FAILED",
        "result.error.code": "ABK0018",
        "result.error.detailedDescription": "The backup of this Kubernetes namespace was not successful because of a problem on the protection storage.",
        "result.error.extendedReason": "Unable to setup backup.  Unable to create directory 'Kubernetes_Backups_-_TEST_PLC-ppdm-01-a2e89/PLCTLP-694fb9a3-e763-4352-8b08-e0b323f863f0/Stagings/e6e4041f-3e15-47bf-b03c-9128d568a63c/mongo/1731594898615410508':  [5005] No space left on device",
        "result.error.reason": "Unable to back up namespace 'mongo' in Kubernetes cluster 'Cluster-01' because of a protection storage issue.",
        "result.error.remediation": "Verify that the PowerProtect DD System is fully functional and that the DD Boost ports are open between the Kubernetes cluster and the PowerProtect DD System.",
        "asset.name": "mongo",
        "asset.type": "KUBERNETES",
        "host.name": null,
        "host.type": null,
        "inventorySource.type": "KUBERNETES",
        "protectionPolicy.name": "Kubernetes Backups - TEST PLC",
        "protectionPolicy.type": "KUBERNETES",
        "createTime": "2024-11-14T14:34:02.907Z",
        "endTime": "2024-11-14T14:34:51.768Z"
    },
    {
        "category": "PROTECT",
        "classType": "JOB",
        "result.status": "FAILED",
        "result.error.code": "AERR0019",
        "result.error.detailedDescription": "This task is unsuccessful because internal issue happens at service side.",
        "result.error.extendedReason": null,
        "result.error.reason": "This task is unsuccessful because internal issue happens at service side.",
        "result.error.remediation": "To troubleshoot this issue: wait for some time and then retry the operation again. If the issue persists, contact Dell Customer Support.",
        "asset.name": "linux-03",
        "asset.type": "VMWARE_VIRTUAL_MACHINE",
        "host.name": null,
        "host.type": null,
        "inventorySource.type": "VCENTER",
        "protectionPolicy.name": "Virtual Machines -Crash consistent -Test PLC",
        "protectionPolicy.type": "VMWARE_VIRTUAL_MACHINE",
        "createTime": "2024-11-14T14:34:21.546Z",
        "endTime": "2024-11-14T14:35:02.369Z"
    },
    {
        "category": "PROTECT",
        "classType": "JOB",
        "result.status": "FAILED",
        "result.error.code": "ABA0002",
        "result.error.detailedDescription": "The protection policy backup was unsuccessful because of an agent issue.",
        "result.error.extendedReason": "Protection policy backup was unsuccessful because the Agent failed with the following error: Backup of database on host and instance is unsuccessful because of an internal server error. Check the ddbmsqlsv logs available in MSAPPAGENT logs directory on the host for more details.",
        "result.error.reason": "SQL Backups -TEST PLC: Unable to backup MICROSOFT_SQL_DATABASE asset msdb on host sqlaag-01.demo.local to storage target SQL_Backups_-TEST_PLC-ppdm-01-f0af0 because of an agent issue.",
        "result.error.remediation": "Click export log and review the log file to determine the status of the job or check agent logs for more details.",
        "asset.name": "msdb",
        "asset.type": "MICROSOFT_SQL_DATABASE",
        "host.name": "sqlaag-01.demo.local",
        "host.type": "APP_HOST",
        "inventorySource.type": null,
        "protectionPolicy.name": "SQL Backups -TEST PLC",
        "protectionPolicy.type": "MICROSOFT_SQL_DATABASE",
        "createTime": "2024-11-14T14:34:15.306Z",
        "endTime": "2024-11-14T14:35:03.130Z"
    },
    {
        "category": "PROTECT",
        "classType": "TASK",
        "result.status": "FAILED",
        "result.error.code": "ABA0002",
        "result.error.detailedDescription": "The protection policy backup was unsuccessful because of an agent issue.",
        "result.error.extendedReason": "Protection policy backup was unsuccessful because the Agent failed with the following error: Backup of database on host and instance is unsuccessful because of an internal server error. Check the ddbmsqlsv logs available in MSAPPAGENT logs directory on the host for more details.",
        "result.error.reason": "SQL Backups -TEST PLC: Unable to backup MICROSOFT_SQL_DATABASE asset model on host sqlaag-01.demo.local to storage target SQL_Backups_-TEST_PLC-ppdm-01-f0af0 because of an agent issue.",
        "result.error.remediation": "Click export log and review the log file to determine the status of the job or check agent logs for more details.",
        "asset.name": "model",
        "asset.type": null,
        "host.name": "sqlaag-01.demo.local",
        "host.type": null,
        "inventorySource.type": null,
        "protectionPolicy.name": "SQL Backups -TEST PLC",
        "protectionPolicy.type": null,
        "createTime": "2024-11-14T14:34:18.798Z",
        "endTime": "2024-11-14T14:35:02.688Z"
    },
    {
        "category": "PROTECT",
        "classType": "TASK",
        "result.status": "FAILED",
        "result.error.code": "ABA0002",
        "result.error.detailedDescription": "The protection policy backup was unsuccessful because of an agent issue.",
        "result.error.extendedReason": "Protection policy backup was unsuccessful because the Agent failed with the following error: Backup of database on host and instance is unsuccessful because of an internal server error. Check the ddbmsqlsv logs available in MSAPPAGENT logs directory on the host for more details.",
        "result.error.reason": "SQL Backups -TEST PLC: Unable to backup MICROSOFT_SQL_DATABASE asset msdb on host sqlaag-01.demo.local to storage target SQL_Backups_-TEST_PLC-ppdm-01-f0af0 because of an agent issue.",
        "result.error.remediation": "Click export log and review the log file to determine the status of the job or check agent logs for more details.",
        "asset.name": "msdb",
        "asset.type": null,
        "host.name": "sqlaag-01.demo.local",
        "host.type": null,
        "inventorySource.type": null,
        "protectionPolicy.name": "SQL Backups -TEST PLC",
        "protectionPolicy.type": null,
        "createTime": "2024-11-14T14:34:18.932Z",
        "endTime": "2024-11-14T14:35:02.698Z"
    },
    {
        "category": "PROTECT",
        "classType": "TASK",
        "result.status": "FAILED",
        "result.error.code": "ABV0026",
        "result.error.detailedDescription": "The VM Direct engine cannot complete the backup of this virtual machine because of a protection storage capacity issue on the PowerProtect DD.",
        "result.error.extendedReason": "Cannot create export directory 'Virtual_Machines_-Crash_consistent_--ppdm-01-ef2c3/PLCTLP-526629ba-5227-4c6f-a26d-0ff368976ef4/Stagings/4c6e8a0d-b323-44bf-b12b-da850be18bc5/501efedb-2483-f721-7018-f38280375d3a/1731594897900740675' on 'ddve-01.demo.local':  [5005] No space left on device",
        "result.error.reason": "The VM Direct engine 'localhost' is unable to back up the virtual machine 'linux-03' on vCenter 'VCenter' because the available space on the protection storage system 'ddve-01.demo.local' is insufficient.",
        "result.error.remediation": "Check the protection storage system to determine if there is enough free space for the operation. The PowerProtect DD Administration Guide provides more information on how to reclaim space.",
        "asset.name": "linux-03",
        "asset.type": null,
        "host.name": "esxi01-7.demo.local",
        "host.type": null,
        "inventorySource.type": null,
        "protectionPolicy.name": "Virtual Machines -Crash consistent -Test PLC",
        "protectionPolicy.type": null,
        "createTime": "2024-11-14T14:34:53.213Z",
        "endTime": "2024-11-14T14:35:01.767Z"
    },
    {
        "category": "PROTECT",
        "classType": "TASK",
        "result.status": "FAILED",
        "result.error.code": "ABV0026",
        "result.error.detailedDescription": "The VM Direct engine cannot complete the backup of this virtual machine because of a protection storage capacity issue on the PowerProtect DD.",
        "result.error.extendedReason": "Cannot create export directory 'Virtual_Machines_-Crash_consistent_--ppdm-01-ef2c3/PLCTLP-526629ba-5227-4c6f-a26d-0ff368976ef4/Stagings/4c6e8a0d-b323-44bf-b12b-da850be18bc5/5000aeb5-5fa2-2c47-8551-77cf41c35fbc/1731594900275472472' on 'ddve-01.demo.local':  [5005] No space left on device",
        "result.error.reason": "The VM Direct engine 'localhost' is unable to back up the virtual machine 'LINUX-01' on vCenter 'VCenter' because the available space on the protection storage system 'ddve-01.demo.local' is insufficient.",
        "result.error.remediation": "Check the protection storage system to determine if there is enough free space for the operation. The PowerProtect DD Administration Guide provides more information on how to reclaim space.",
        "asset.name": "LINUX-01",
        "asset.type": null,
        "host.name": "esxi03-7.demo.local",
        "host.type": null,
        "inventorySource.type": null,
        "protectionPolicy.name": "Virtual Machines -Crash consistent -Test PLC",
        "protectionPolicy.type": null,
        "createTime": "2024-11-14T14:34:53.201Z",
        "endTime": "2024-11-14T14:35:04.251Z"
    },
    {
        "category": "PROTECT",
        "classType": "TASK",
        "result.status": "FAILED",
        "result.error.code": "ABV0026",
        "result.error.detailedDescription": "The VM Direct engine cannot complete the backup of this virtual machine because of a protection storage capacity issue on the PowerProtect DD.",
        "result.error.extendedReason": "Cannot create export directory 'Virtual_Machines_-Crash_consistent_--ppdm-01-ef2c3/PLCTLP-526629ba-5227-4c6f-a26d-0ff368976ef4/Stagings/4c6e8a0d-b323-44bf-b12b-da850be18bc5/50006349-b0a4-eac9-cf56-45749ecec84b/1731594900218095259' on 'ddve-01.demo.local':  [5005] No space left on device",
        "result.error.reason": "The VM Direct engine 'localhost' is unable to back up the virtual machine 'WIN-01' on vCenter 'VCenter' because the available space on the protection storage system 'ddve-01.demo.local' is insufficient.",
        "result.error.remediation": "Check the protection storage system to determine if there is enough free space for the operation. The PowerProtect DD Administration Guide provides more information on how to reclaim space.",
        "asset.name": "WIN-01",
        "asset.type": null,
        "host.name": "esxi03-7.demo.local",
        "host.type": null,
        "inventorySource.type": null,
        "protectionPolicy.name": "Virtual Machines -Crash consistent -Test PLC",
        "protectionPolicy.type": null,
        "createTime": "2024-11-14T14:34:53.214Z",
        "endTime": "2024-11-14T14:35:04.214Z"
    },
    {
        "category": "PROTECT",
        "classType": "TASK",
        "result.status": "FAILED",
        "result.error.code": "ABV0026",
        "result.error.detailedDescription": "The VM Direct engine cannot complete the backup of this virtual machine because of a protection storage capacity issue on the PowerProtect DD.",
        "result.error.extendedReason": "Cannot create export directory 'Virtual_Machines_-Crash_consistent_--ppdm-01-ef2c3/PLCTLP-526629ba-5227-4c6f-a26d-0ff368976ef4/Stagings/4c6e8a0d-b323-44bf-b12b-da850be18bc5/501f8827-9901-b519-d7a2-e964acb1c966/1731594900082186001' on 'ddve-01.demo.local':  [5005] No space left on device",
        "result.error.reason": "The VM Direct engine 'localhost' is unable to back up the virtual machine 'RSA_Authentication_Manager.x86_64-8.7.0' on vCenter 'VCenter' because the available space on the protection storage system 'ddve-01.demo.local' is insufficient.",
        "result.error.remediation": "Check the protection storage system to determine if there is enough free space for the operation. The PowerProtect DD Administration Guide provides more information on how to reclaim space.",
        "asset.name": "RSA_Authentication_Manager.x86_64-8.7.0",
        "asset.type": null,
        "host.name": "esxi03-7.demo.local",
        "host.type": null,
        "inventorySource.type": null,
        "protectionPolicy.name": "Virtual Machines -Crash consistent -Test PLC",
        "protectionPolicy.type": null,
        "createTime": "2024-11-14T14:34:53.224Z",
        "endTime": "2024-11-14T14:35:04.105Z"
    },
    {
        "category": "PROTECT",
        "classType": "TASK",
        "result.status": "FAILED",
        "result.error.code": "ABV0026",
        "result.error.detailedDescription": "The VM Direct engine cannot complete the backup of this virtual machine because of a protection storage capacity issue on the PowerProtect DD.",
        "result.error.extendedReason": "Cannot create export directory 'Virtual_Machines_-Crash_consistent_--ppdm-01-ef2c3/PLCTLP-526629ba-5227-4c6f-a26d-0ff368976ef4/Stagings/4c6e8a0d-b323-44bf-b12b-da850be18bc5/50001429-b25c-d954-ca16-7f588e4224fc/1731594900393976106' on 'ddve-01.demo.local':  [5005] No space left on device",
        "result.error.reason": "The VM Direct engine 'localhost' is unable to back up the virtual machine 'WIN-02' on vCenter 'VCenter' because the available space on the protection storage system 'ddve-01.demo.local' is insufficient.",
        "result.error.remediation": "Check the protection storage system to determine if there is enough free space for the operation. The PowerProtect DD Administration Guide provides more information on how to reclaim space.",
        "asset.name": "WIN-02",
        "asset.type": null,
        "host.name": "esxi03-7.demo.local",
        "host.type": null,
        "inventorySource.type": null,
        "protectionPolicy.name": "Virtual Machines -Crash consistent -Test PLC",
        "protectionPolicy.type": null,
        "createTime": "2024-11-14T14:34:53.201Z",
        "endTime": "2024-11-14T14:35:04.388Z"
    },
    {
        "category": "PROTECT",
        "classType": "JOB",
        "result.status": "FAILED",
        "result.error.code": "AERR0019",
        "result.error.detailedDescription": "This task is unsuccessful because internal issue happens at service side.",
        "result.error.extendedReason": null,
        "result.error.reason": "This task is unsuccessful because internal issue happens at service side.",
        "result.error.remediation": "To troubleshoot this issue: wait for some time and then retry the operation again. If the issue persists, contact Dell Customer Support.",
        "asset.name": "RSA_Authentication_Manager.x86_64-8.7.0",
        "asset.type": "VMWARE_VIRTUAL_MACHINE",
        "host.name": null,
        "host.type": null,
        "inventorySource.type": "VCENTER",
        "protectionPolicy.name": "Virtual Machines -Crash consistent -Test PLC",
        "protectionPolicy.type": "VMWARE_VIRTUAL_MACHINE",
        "createTime": "2024-11-14T14:34:24.545Z",
        "endTime": "2024-11-14T14:35:04.821Z"
    },
    {
        "category": "PROTECT",
        "classType": "JOB",
        "result.status": "FAILED",
        "result.error.code": "AERR0019",
        "result.error.detailedDescription": "This task is unsuccessful because internal issue happens at service side.",
        "result.error.extendedReason": null,
        "result.error.reason": "This task is unsuccessful because internal issue happens at service side.",
        "result.error.remediation": "To troubleshoot this issue: wait for some time and then retry the operation again. If the issue persists, contact Dell Customer Support.",
        "asset.name": "sqlaag-01",
        "asset.type": "VMWARE_VIRTUAL_MACHINE",
        "host.name": null,
        "host.type": null,
        "inventorySource.type": "VCENTER",
        "protectionPolicy.name": "Virtual Machines -Crash consistent -Test PLC",
        "protectionPolicy.type": "VMWARE_VIRTUAL_MACHINE",
        "createTime": "2024-11-14T14:34:23.187Z",
        "endTime": "2024-11-14T14:35:04.661Z"
    },
    {
        "category": "PROTECT",
        "classType": "JOB",
        "result.status": "FAILED",
        "result.error.code": "AERR0019",
        "result.error.detailedDescription": "This task is unsuccessful because internal issue happens at service side.",
        "result.error.extendedReason": null,
        "result.error.reason": "This task is unsuccessful because internal issue happens at service side.",
        "result.error.remediation": "To troubleshoot this issue: wait for some time and then retry the operation again. If the issue persists, contact Dell Customer Support.",
        "asset.name": "SQL-03",
        "asset.type": "VMWARE_VIRTUAL_MACHINE",
        "host.name": null,
        "host.type": null,
        "inventorySource.type": "VCENTER",
        "protectionPolicy.name": "Virtual Machines -Crash consistent -Test PLC",
        "protectionPolicy.type": "VMWARE_VIRTUAL_MACHINE",
        "createTime": "2024-11-14T14:34:23.481Z",
        "endTime": "2024-11-14T14:35:04.653Z"
    },
    {
        "category": "PROTECT",
        "classType": "JOB",
        "result.status": "FAILED",
        "result.error.code": "AERR0019",
        "result.error.detailedDescription": "This task is unsuccessful because internal issue happens at service side.",
        "result.error.extendedReason": null,
        "result.error.reason": "This task is unsuccessful because internal issue happens at service side.",
        "result.error.remediation": "To troubleshoot this issue: wait for some time and then retry the operation again. If the issue persists, contact Dell Customer Support.",
        "asset.name": "Isilon",
        "asset.type": "VMWARE_VIRTUAL_MACHINE",
        "host.name": null,
        "host.type": null,
        "inventorySource.type": "VCENTER",
        "protectionPolicy.name": "Virtual Machines -Crash consistent -Test PLC",
        "protectionPolicy.type": "VMWARE_VIRTUAL_MACHINE",
        "createTime": "2024-11-14T14:34:25.631Z",
        "endTime": "2024-11-14T14:35:04.661Z"
    },
    {
        "category": "PROTECT",
        "classType": "JOB",
        "result.status": "FAILED",
        "result.error.code": "AERR0019",
        "result.error.detailedDescription": "This task is unsuccessful because internal issue happens at service side.",
        "result.error.extendedReason": null,
        "result.error.reason": "This task is unsuccessful because internal issue happens at service side.",
        "result.error.remediation": "To troubleshoot this issue: wait for some time and then retry the operation again. If the issue persists, contact Dell Customer Support.",
        "asset.name": "WIN-02",
        "asset.type": "VMWARE_VIRTUAL_MACHINE",
        "host.name": null,
        "host.type": null,
        "inventorySource.type": "VCENTER",
        "protectionPolicy.name": "Virtual Machines -Crash consistent -Test PLC",
        "protectionPolicy.type": "VMWARE_VIRTUAL_MACHINE",
        "createTime": "2024-11-14T14:34:24.195Z",
        "endTime": "2024-11-14T14:35:05.262Z"
    },
    {
        "category": "PROTECT",
        "classType": "JOB",
        "result.status": "FAILED",
        "result.error.code": "AERR0019",
        "result.error.detailedDescription": "This task is unsuccessful because internal issue happens at service side.",
        "result.error.extendedReason": null,
        "result.error.reason": "This task is unsuccessful because internal issue happens at service side.",
        "result.error.remediation": "To troubleshoot this issue: wait for some time and then retry the operation again. If the issue persists, contact Dell Customer Support.",
        "asset.name": "WIN-01",
        "asset.type": "VMWARE_VIRTUAL_MACHINE",
        "host.name": null,
        "host.type": null,
        "inventorySource.type": "VCENTER",
        "protectionPolicy.name": "Virtual Machines -Crash consistent -Test PLC",
        "protectionPolicy.type": "VMWARE_VIRTUAL_MACHINE",
        "createTime": "2024-11-14T14:34:22.273Z",
        "endTime": "2024-11-14T14:35:05.089Z"
    },
    {
        "category": "PROTECT",
        "classType": "JOB",
        "result.status": "FAILED",
        "result.error.code": "AERR0019",
        "result.error.detailedDescription": "This task is unsuccessful because internal issue happens at service side.",
        "result.error.extendedReason": null,
        "result.error.reason": "This task is unsuccessful because internal issue happens at service side.",
        "result.error.remediation": "To troubleshoot this issue: wait for some time and then retry the operation again. If the issue persists, contact Dell Customer Support.",
        "asset.name": "LINUX-01",
        "asset.type": "VMWARE_VIRTUAL_MACHINE",
        "host.name": null,
        "host.type": null,
        "inventorySource.type": "VCENTER",
        "protectionPolicy.name": "Virtual Machines -Crash consistent -Test PLC",
        "protectionPolicy.type": "VMWARE_VIRTUAL_MACHINE",
        "createTime": "2024-11-14T14:34:25.280Z",
        "endTime": "2024-11-14T14:35:04.977Z"
    },
    {
        "category": "PROTECT",
        "classType": "JOB",
        "result.status": "FAILED",
        "result.error.code": "ABK0018",
        "result.error.detailedDescription": "The backup of this Kubernetes namespace was not successful because of a problem on the protection storage.",
        "result.error.extendedReason": "Unable to setup backup.  Unable to create directory 'Kubernetes_Backups_-_TEST_PLC-ppdm-01-a2e89/PLCTLP-694fb9a3-e763-4352-8b08-e0b323f863f0/Stagings/e6e4041f-3e15-47bf-b03c-9128d568a63c/default/1731594922824007366':  [5005] No space left on device",
        "result.error.reason": "Unable to back up namespace 'default' in Kubernetes cluster 'Cluster-01' because of a protection storage issue.",
        "result.error.remediation": "Verify that the PowerProtect DD System is fully functional and that the DD Boost ports are open between the Kubernetes cluster and the PowerProtect DD System.",
        "asset.name": "default",
        "asset.type": "KUBERNETES",
        "host.name": null,
        "host.type": null,
        "inventorySource.type": "KUBERNETES",
        "protectionPolicy.name": "Kubernetes Backups - TEST PLC",
        "protectionPolicy.type": "KUBERNETES",
        "createTime": "2024-11-14T14:34:03.319Z",
        "endTime": "2024-11-14T14:35:17.772Z"
    },
    {
        "category": "PROTECT",
        "classType": "TASK",
        "result.status": "FAILED",
        "result.error.code": "ABA0002",
        "result.error.detailedDescription": "The protection policy backup was unsuccessful because of an agent issue.",
        "result.error.extendedReason": "Protection policy backup was unsuccessful because the Agent failed with the following error: Backup of database on host and instance is unsuccessful because of an internal server error. Check the ddbmsqlsv logs available in MSAPPAGENT logs directory on the host for more details.",
        "result.error.reason": "SQL Backups -TEST PLC: Unable to backup MICROSOFT_SQL_DATABASE asset msdb on host sqlaag-02.demo.local to storage target SQL_Backups_-TEST_PLC-ppdm-01-f0af0 because of an agent issue.",
        "result.error.remediation": "Click export log and review the log file to determine the status of the job or check agent logs for more details.",
        "asset.name": "msdb",
        "asset.type": null,
        "host.name": "sqlaag-02.demo.local",
        "host.type": null,
        "inventorySource.type": null,
        "protectionPolicy.name": "SQL Backups -TEST PLC",
        "protectionPolicy.type": null,
        "createTime": "2024-11-14T14:34:18.942Z",
        "endTime": "2024-11-14T14:35:31.275Z"
    },
    {
        "category": "PROTECT",
        "classType": "TASK",
        "result.status": "FAILED",
        "result.error.code": "ABA0002",
        "result.error.detailedDescription": "The protection policy backup was unsuccessful because of an agent issue.",
        "result.error.extendedReason": "Protection policy backup was unsuccessful because the Agent failed with the following error: Backup of database on host and instance is unsuccessful because of an internal server error. Check the ddbmsqlsv logs available in MSAPPAGENT logs directory on the host for more details.",
        "result.error.reason": "SQL Backups -TEST PLC: Unable to backup MICROSOFT_SQL_DATABASE asset model on host sqlaag-02.demo.local to storage target SQL_Backups_-TEST_PLC-ppdm-01-f0af0 because of an agent issue.",
        "result.error.remediation": "Click export log and review the log file to determine the status of the job or check agent logs for more details.",
        "asset.name": "model",
        "asset.type": null,
        "host.name": "sqlaag-02.demo.local",
        "host.type": null,
        "inventorySource.type": null,
        "protectionPolicy.name": "SQL Backups -TEST PLC",
        "protectionPolicy.type": null,
        "createTime": "2024-11-14T14:34:18.800Z",
        "endTime": "2024-11-14T14:35:31.284Z"
    },
    {
        "category": "PROTECT",
        "classType": "JOB",
        "result.status": "FAILED",
        "result.error.code": "ABA0002",
        "result.error.detailedDescription": "The protection policy backup was unsuccessful because of an agent issue.",
        "result.error.extendedReason": "Protection policy backup was unsuccessful because the Agent failed with the following error: Backup of database on host and instance is unsuccessful because of an internal server error. Check the ddbmsqlsv logs available in MSAPPAGENT logs directory on the host for more details.",
        "result.error.reason": "SQL Backups -TEST PLC: Unable to backup MICROSOFT_SQL_DATABASE asset msdb on host sqlaag-02.demo.local to storage target SQL_Backups_-TEST_PLC-ppdm-01-f0af0 because of an agent issue.",
        "result.error.remediation": "Click export log and review the log file to determine the status of the job or check agent logs for more details.",
        "asset.name": "msdb",
        "asset.type": "MICROSOFT_SQL_DATABASE",
        "host.name": "sqlaag-02.demo.local",
        "host.type": "APP_HOST",
        "inventorySource.type": null,
        "protectionPolicy.name": "SQL Backups -TEST PLC",
        "protectionPolicy.type": "MICROSOFT_SQL_DATABASE",
        "createTime": "2024-11-14T14:34:15.625Z",
        "endTime": "2024-11-14T14:35:31.901Z"
    },
    {
        "category": "PROTECT",
        "classType": "JOB",
        "result.status": "FAILED",
        "result.error.code": "ABA0002",
        "result.error.detailedDescription": "The protection policy backup was unsuccessful because of an agent issue.",
        "result.error.extendedReason": "Protection policy backup was unsuccessful because the Agent failed with the following error: Backup of database on host and instance is unsuccessful because of an internal server error. Check the ddbmsqlsv logs available in MSAPPAGENT logs directory on the host for more details.",
        "result.error.reason": "SQL Backups -TEST PLC: Unable to backup MICROSOFT_SQL_DATABASE asset DemoDB-01 on host sqlaag-02.demo.local to storage target SQL_Backups_-TEST_PLC-ppdm-01-f0af0 because of an agent issue.",
        "result.error.remediation": "Click export log and review the log file to determine the status of the job or check agent logs for more details.",
        "asset.name": "DemoDB-01",
        "asset.type": "MICROSOFT_SQL_DATABASE",
        "host.name": "sqlaag-02.demo.local",
        "host.type": "APP_HOST",
        "inventorySource.type": null,
        "protectionPolicy.name": "SQL Backups -TEST PLC",
        "protectionPolicy.type": "MICROSOFT_SQL_DATABASE",
        "createTime": "2024-11-14T14:34:17.197Z",
        "endTime": "2024-11-14T14:35:32.681Z"
    },
    {
        "category": "PROTECT",
        "classType": "TASK",
        "result.status": "FAILED",
        "result.error.code": "ABA0002",
        "result.error.detailedDescription": "The protection policy backup was unsuccessful because of an agent issue.",
        "result.error.extendedReason": "Protection policy backup was unsuccessful because the Agent failed with the following error: Backup of database on host and instance is unsuccessful because of an internal server error. Check the ddbmsqlsv logs available in MSAPPAGENT logs directory on the host for more details.",
        "result.error.reason": "SQL Backups -TEST PLC: Unable to backup MICROSOFT_SQL_DATABASE asset DemoDB-02 on host sqlaag-02.demo.local to storage target SQL_Backups_-TEST_PLC-ppdm-01-f0af0 because of an agent issue.",
        "result.error.remediation": "Click export log and review the log file to determine the status of the job or check agent logs for more details.",
        "asset.name": "DemoDB-02",
        "asset.type": null,
        "host.name": "sqlaag-02.demo.local",
        "host.type": null,
        "inventorySource.type": null,
        "protectionPolicy.name": "SQL Backups -TEST PLC",
        "protectionPolicy.type": null,
        "createTime": "2024-11-14T14:34:18.799Z",
        "endTime": "2024-11-14T14:35:31.539Z"
    },
    {
        "category": "PROTECT",
        "classType": "TASK",
        "result.status": "FAILED",
        "result.error.code": "ABV0026",
        "result.error.detailedDescription": "The VM Direct engine cannot complete the backup of this virtual machine because of a protection storage capacity issue on the PowerProtect DD.",
        "result.error.extendedReason": "Cannot create export directory 'Virtual_Machines_-Crash_consistent_--ppdm-01-ef2c3/PLCTLP-526629ba-5227-4c6f-a26d-0ff368976ef4/Stagings/4c6e8a0d-b323-44bf-b12b-da850be18bc5/501f1b61-1a78-75a2-de97-6d802f87a084/1731594927473478151' on 'ddve-01.demo.local':  [5005] No space left on device",
        "result.error.reason": "The VM Direct engine 'localhost' is unable to back up the virtual machine 'PPDM-01' on vCenter 'VCenter' because the available space on the protection storage system 'ddve-01.demo.local' is insufficient.",
        "result.error.remediation": "Check the protection storage system to determine if there is enough free space for the operation. The PowerProtect DD Administration Guide provides more information on how to reclaim space.",
        "asset.name": "PPDM-01",
        "asset.type": null,
        "host.name": "esxi01-7.demo.local",
        "host.type": null,
        "inventorySource.type": null,
        "protectionPolicy.name": "Virtual Machines -Crash consistent -Test PLC",
        "protectionPolicy.type": null,
        "createTime": "2024-11-14T14:35:25.115Z",
        "endTime": "2024-11-14T14:35:31.531Z"
    },
    {
        "category": "PROTECT",
        "classType": "JOB",
        "result.status": "FAILED",
        "result.error.code": "ABA0002",
        "result.error.detailedDescription": "The protection policy backup was unsuccessful because of an agent issue.",
        "result.error.extendedReason": "Protection policy backup was unsuccessful because the Agent failed with the following error: Backup of database on host and instance is unsuccessful because of an internal server error. Check the ddbmsqlsv logs available in MSAPPAGENT logs directory on the host for more details.",
        "result.error.reason": "SQL Backups -TEST PLC: Unable to backup MICROSOFT_SQL_DATABASE asset DemoDB-02 on host sqlaag-02.demo.local to storage target SQL_Backups_-TEST_PLC-ppdm-01-f0af0 because of an agent issue.",
        "result.error.remediation": "Click export log and review the log file to determine the status of the job or check agent logs for more details.",
        "asset.name": "DemoDB-02",
        "asset.type": "MICROSOFT_SQL_DATABASE",
        "host.name": "sqlaag-02.demo.local",
        "host.type": "APP_HOST",
        "inventorySource.type": null,
        "protectionPolicy.name": "SQL Backups -TEST PLC",
        "protectionPolicy.type": "MICROSOFT_SQL_DATABASE",
        "createTime": "2024-11-14T14:34:17.030Z",
        "endTime": "2024-11-14T14:35:32.935Z"
    },
    {
        "category": "PROTECT",
        "classType": "TASK",
        "result.status": "FAILED",
        "result.error.code": "ABA0002",
        "result.error.detailedDescription": "The protection policy backup was unsuccessful because of an agent issue.",
        "result.error.extendedReason": "Protection policy backup was unsuccessful because the Agent failed with the following error: Backup of database on host and instance is unsuccessful because of an internal server error. Check the ddbmsqlsv logs available in MSAPPAGENT logs directory on the host for more details.",
        "result.error.reason": "SQL Backups -TEST PLC: Unable to backup MICROSOFT_SQL_DATABASE asset SQLPROD-01 on host SQL-02.demo.local to storage target SQL_Backups_-TEST_PLC-ppdm-01-f0af0 because of an agent issue.",
        "result.error.remediation": "Click export log and review the log file to determine the status of the job or check agent logs for more details.",
        "asset.name": "SQLPROD-01",
        "asset.type": null,
        "host.name": "SQL-02.demo.local",
        "host.type": null,
        "inventorySource.type": null,
        "protectionPolicy.name": "SQL Backups -TEST PLC",
        "protectionPolicy.type": null,
        "createTime": "2024-11-14T14:34:18.988Z",
        "endTime": "2024-11-14T14:35:34.159Z"
    },
    {
        "category": "PROTECT",
        "classType": "JOB",
        "result.status": "FAILED",
        "result.error.code": "ABA0002",
        "result.error.detailedDescription": "The protection policy backup was unsuccessful because of an agent issue.",
        "result.error.extendedReason": "Protection policy backup was unsuccessful because the Agent failed with the following error: Backup of database on host and instance is unsuccessful because of an internal server error. Check the ddbmsqlsv logs available in MSAPPAGENT logs directory on the host for more details.",
        "result.error.reason": "SQL Backups -TEST PLC: Unable to backup MICROSOFT_SQL_DATABASE asset SQLQA-01 on host SQL-02.demo.local to storage target SQL_Backups_-TEST_PLC-ppdm-01-f0af0 because of an agent issue.",
        "result.error.remediation": "Click export log and review the log file to determine the status of the job or check agent logs for more details.",
        "asset.name": "SQLQA-01",
        "asset.type": "MICROSOFT_SQL_DATABASE",
        "host.name": "SQL-02.demo.local",
        "host.type": "APP_HOST",
        "inventorySource.type": null,
        "protectionPolicy.name": "SQL Backups -TEST PLC",
        "protectionPolicy.type": "MICROSOFT_SQL_DATABASE",
        "createTime": "2024-11-14T14:34:14.256Z",
        "endTime": "2024-11-14T14:35:35.060Z"
    },
    {
        "category": "PROTECT",
        "classType": "TASK",
        "result.status": "FAILED",
        "result.error.code": "ABA0002",
        "result.error.detailedDescription": "The protection policy backup was unsuccessful because of an agent issue.",
        "result.error.extendedReason": "Protection policy backup was unsuccessful because the Agent failed with the following error: Backup of database on host and instance is unsuccessful because of an internal server error. Check the ddbmsqlsv logs available in MSAPPAGENT logs directory on the host for more details.",
        "result.error.reason": "SQL Backups -TEST PLC: Unable to backup MICROSOFT_SQL_DATABASE asset SQLQA-02 on host SQL-02.demo.local to storage target SQL_Backups_-TEST_PLC-ppdm-01-f0af0 because of an agent issue.",
        "result.error.remediation": "Click export log and review the log file to determine the status of the job or check agent logs for more details.",
        "asset.name": "SQLQA-02",
        "asset.type": null,
        "host.name": "SQL-02.demo.local",
        "host.type": null,
        "inventorySource.type": null,
        "protectionPolicy.name": "SQL Backups -TEST PLC",
        "protectionPolicy.type": null,
        "createTime": "2024-11-14T14:34:18.799Z",
        "endTime": "2024-11-14T14:35:34.172Z"
    },
    {
        "category": "PROTECT",
        "classType": "JOB",
        "result.status": "FAILED",
        "result.error.code": "ABA0002",
        "result.error.detailedDescription": "The protection policy backup was unsuccessful because of an agent issue.",
        "result.error.extendedReason": "Protection policy backup was unsuccessful because the Agent failed with the following error: Backup of database on host and instance is unsuccessful because of an internal server error. Check the ddbmsqlsv logs available in MSAPPAGENT logs directory on the host for more details.",
        "result.error.reason": "SQL Backups -TEST PLC: Unable to backup MICROSOFT_SQL_DATABASE asset SQLQA-03 on host SQL-02.demo.local to storage target SQL_Backups_-TEST_PLC-ppdm-01-f0af0 because of an agent issue.",
        "result.error.remediation": "Click export log and review the log file to determine the status of the job or check agent logs for more details.",
        "asset.name": "SQLQA-03",
        "asset.type": "MICROSOFT_SQL_DATABASE",
        "host.name": "SQL-02.demo.local",
        "host.type": "APP_HOST",
        "inventorySource.type": null,
        "protectionPolicy.name": "SQL Backups -TEST PLC",
        "protectionPolicy.type": "MICROSOFT_SQL_DATABASE",
        "createTime": "2024-11-14T14:34:16.267Z",
        "endTime": "2024-11-14T14:35:35.248Z"
    },
    {
        "category": "PROTECT",
        "classType": "TASK",
        "result.status": "FAILED",
        "result.error.code": "ABA0002",
        "result.error.detailedDescription": "The protection policy backup was unsuccessful because of an agent issue.",
        "result.error.extendedReason": "Protection policy backup was unsuccessful because the Agent failed with the following error: Backup of database on host and instance is unsuccessful because of an internal server error. Check the ddbmsqlsv logs available in MSAPPAGENT logs directory on the host for more details.",
        "result.error.reason": "SQL Backups -TEST PLC: Unable to backup MICROSOFT_SQL_DATABASE asset SQLDEV-01 on host SQL-02.demo.local to storage target SQL_Backups_-TEST_PLC-ppdm-01-f0af0 because of an agent issue.",
        "result.error.remediation": "Click export log and review the log file to determine the status of the job or check agent logs for more details.",
        "asset.name": "SQLDEV-01",
        "asset.type": null,
        "host.name": "SQL-02.demo.local",
        "host.type": null,
        "inventorySource.type": null,
        "protectionPolicy.name": "SQL Backups -TEST PLC",
        "protectionPolicy.type": null,
        "createTime": "2024-11-14T14:34:18.951Z",
        "endTime": "2024-11-14T14:35:34.177Z"
    },
    {
        "category": "PROTECT",
        "classType": "JOB",
        "result.status": "FAILED",
        "result.error.code": "ABA0002",
        "result.error.detailedDescription": "The protection policy backup was unsuccessful because of an agent issue.",
        "result.error.extendedReason": "Protection policy backup was unsuccessful because the Agent failed with the following error: Backup of database on host and instance is unsuccessful because of an internal server error. Check the ddbmsqlsv logs available in MSAPPAGENT logs directory on the host for more details.",
        "result.error.reason": "SQL Backups -TEST PLC: Unable to backup MICROSOFT_SQL_DATABASE asset SQLDEV-01 on host SQL-02.demo.local to storage target SQL_Backups_-TEST_PLC-ppdm-01-f0af0 because of an agent issue.",
        "result.error.remediation": "Click export log and review the log file to determine the status of the job or check agent logs for more details.",
        "asset.name": "SQLDEV-01",
        "asset.type": "MICROSOFT_SQL_DATABASE",
        "host.name": "SQL-02.demo.local",
        "host.type": "APP_HOST",
        "inventorySource.type": null,
        "protectionPolicy.name": "SQL Backups -TEST PLC",
        "protectionPolicy.type": "MICROSOFT_SQL_DATABASE",
        "createTime": "2024-11-14T14:34:13.718Z",
        "endTime": "2024-11-14T14:35:35.459Z"
    },
    {
        "category": "PROTECT",
        "classType": "TASK",
        "result.status": "FAILED",
        "result.error.code": "ABA0002",
        "result.error.detailedDescription": "The protection policy backup was unsuccessful because of an agent issue.",
        "result.error.extendedReason": "Protection policy backup was unsuccessful because the Agent failed with the following error: Backup of database on host and instance is unsuccessful because of an internal server error. Check the ddbmsqlsv logs available in MSAPPAGENT logs directory on the host for more details.",
        "result.error.reason": "SQL Backups -TEST PLC: Unable to backup MICROSOFT_SQL_DATABASE asset SQLQA-01 on host SQL-02.demo.local to storage target SQL_Backups_-TEST_PLC-ppdm-01-f0af0 because of an agent issue.",
        "result.error.remediation": "Click export log and review the log file to determine the status of the job or check agent logs for more details.",
        "asset.name": "SQLQA-01",
        "asset.type": null,
        "host.name": "SQL-02.demo.local",
        "host.type": null,
        "inventorySource.type": null,
        "protectionPolicy.name": "SQL Backups -TEST PLC",
        "protectionPolicy.type": null,
        "createTime": "2024-11-14T14:34:18.940Z",
        "endTime": "2024-11-14T14:35:34.139Z"
    },
    {
        "category": "PROTECT",
        "classType": "JOB",
        "result.status": "FAILED",
        "result.error.code": "ABA0002",
        "result.error.detailedDescription": "The protection policy backup was unsuccessful because of an agent issue.",
        "result.error.extendedReason": "Protection policy backup was unsuccessful because the Agent failed with the following error: Backup of database on host and instance is unsuccessful because of an internal server error. Check the ddbmsqlsv logs available in MSAPPAGENT logs directory on the host for more details.",
        "result.error.reason": "SQL Backups -TEST PLC: Unable to backup MICROSOFT_SQL_DATABASE asset SQLPROD-01 on host SQL-02.demo.local to storage target SQL_Backups_-TEST_PLC-ppdm-01-f0af0 because of an agent issue.",
        "result.error.remediation": "Click export log and review the log file to determine the status of the job or check agent logs for more details.",
        "asset.name": "SQLPROD-01",
        "asset.type": "MICROSOFT_SQL_DATABASE",
        "host.name": "SQL-02.demo.local",
        "host.type": "APP_HOST",
        "inventorySource.type": null,
        "protectionPolicy.name": "SQL Backups -TEST PLC",
        "protectionPolicy.type": "MICROSOFT_SQL_DATABASE",
        "createTime": "2024-11-14T14:34:14.069Z",
        "endTime": "2024-11-14T14:35:35.595Z"
    },
    {
        "category": "PROTECT",
        "classType": "JOB",
        "result.status": "FAILED",
        "result.error.code": "ABA0002",
        "result.error.detailedDescription": "The protection policy backup was unsuccessful because of an agent issue.",
        "result.error.extendedReason": "Protection policy backup was unsuccessful because the Agent failed with the following error: Backup of database on host and instance is unsuccessful because of an internal server error. Check the ddbmsqlsv logs available in MSAPPAGENT logs directory on the host for more details.",
        "result.error.reason": "SQL Backups -TEST PLC: Unable to backup MICROSOFT_SQL_DATABASE asset SQLDEV-02 on host SQL-02.demo.local to storage target SQL_Backups_-TEST_PLC-ppdm-01-f0af0 because of an agent issue.",
        "result.error.remediation": "Click export log and review the log file to determine the status of the job or check agent logs for more details.",
        "asset.name": "SQLDEV-02",
        "asset.type": "MICROSOFT_SQL_DATABASE",
        "host.name": "SQL-02.demo.local",
        "host.type": "APP_HOST",
        "inventorySource.type": null,
        "protectionPolicy.name": "SQL Backups -TEST PLC",
        "protectionPolicy.type": "MICROSOFT_SQL_DATABASE",
        "createTime": "2024-11-14T14:34:13.503Z",
        "endTime": "2024-11-14T14:35:36.104Z"
    },
    {
        "category": "PROTECT",
        "classType": "TASK",
        "result.status": "FAILED",
        "result.error.code": "ABA0002",
        "result.error.detailedDescription": "The protection policy backup was unsuccessful because of an agent issue.",
        "result.error.extendedReason": "Protection policy backup was unsuccessful because the Agent failed with the following error: Backup of database on host and instance is unsuccessful because of an internal server error. Check the ddbmsqlsv logs available in MSAPPAGENT logs directory on the host for more details.",
        "result.error.reason": "SQL Backups -TEST PLC: Unable to backup MICROSOFT_SQL_DATABASE asset SQLQA-03 on host SQL-02.demo.local to storage target SQL_Backups_-TEST_PLC-ppdm-01-f0af0 because of an agent issue.",
        "result.error.remediation": "Click export log and review the log file to determine the status of the job or check agent logs for more details.",
        "asset.name": "SQLQA-03",
        "asset.type": null,
        "host.name": "SQL-02.demo.local",
        "host.type": null,
        "inventorySource.type": null,
        "protectionPolicy.name": "SQL Backups -TEST PLC",
        "protectionPolicy.type": null,
        "createTime": "2024-11-14T14:34:18.804Z",
        "endTime": "2024-11-14T14:35:34.181Z"
    },
    {
        "category": "PROTECT",
        "classType": "JOB",
        "result.status": "FAILED",
        "result.error.code": "ABA0002",
        "result.error.detailedDescription": "The protection policy backup was unsuccessful because of an agent issue.",
        "result.error.extendedReason": "Protection policy backup was unsuccessful because the Agent failed with the following error: Backup of database on host and instance is unsuccessful because of an internal server error. Check the ddbmsqlsv logs available in MSAPPAGENT logs directory on the host for more details.",
        "result.error.reason": "SQL Backups -TEST PLC: Unable to backup MICROSOFT_SQL_DATABASE asset master on host SQL-02.demo.local to storage target SQL_Backups_-TEST_PLC-ppdm-01-f0af0 because of an agent issue.",
        "result.error.remediation": "Click export log and review the log file to determine the status of the job or check agent logs for more details.",
        "asset.name": "master",
        "asset.type": "MICROSOFT_SQL_DATABASE",
        "host.name": "SQL-02.demo.local",
        "host.type": "APP_HOST",
        "inventorySource.type": null,
        "protectionPolicy.name": "SQL Backups -TEST PLC",
        "protectionPolicy.type": "MICROSOFT_SQL_DATABASE",
        "createTime": "2024-11-14T14:34:15.152Z",
        "endTime": "2024-11-14T14:35:36.209Z"
    },
    {
        "category": "PROTECT",
        "classType": "TASK",
        "result.status": "FAILED",
        "result.error.code": "ABNA0020",
        "result.error.detailedDescription": "The existence of the target asset cannot be validated.",
        "result.error.extendedReason": "NAS vProxy Engine nas-proxy.demo.local is unable to perform SnapshotAndSlice operation for nasShare /ifs/data/csi/k8s-418144021c. \n\nError Details:\n TaskId: 1e3c2f2e-dba1-44b3-a958-c6ae530a33d0, JobId 1e3c2f2e-dba1-44b3-a958-c6ae530a33d0 \n NAS agent error code 'ABNA0020'. Unable to complete the 'SNAPSHOT_AND_SLICE' operation because the location for asset '/ifs/data/csi/k8s-418144021c' could not be validated in PowerScale/Isilon NAS '192.168.1.108'.. \n",
        "result.error.reason": "Unable to complete a SNAPSHOT_AND_SLICE operation because the location for asset /ifs/data/csi/k8s-418144021c could not be validated in PowerScale/Isilon NAS 192.168.1.108.",
        "result.error.remediation": "Connect to the PowerScale/Isilon NAS and verify that the share exists. \nFrom the PowerProtect Data Manager Asset Source page, perform an on-demand discovery of assets from this asset source.",
        "asset.name": null,
        "asset.type": "NAS_SHARE",
        "host.name": null,
        "host.type": null,
        "inventorySource.type": null,
        "protectionPolicy.name": "NAS Backups - TEST PLC",
        "protectionPolicy.type": "NAS_SHARE",
        "createTime": "2024-11-14T14:34:08.292Z",
        "endTime": "2024-11-14T14:35:43.083Z"
    },
    {
        "category": "PROTECT",
        "classType": "TASK",
        "result.status": "SKIPPED",
        "result.error.code": "AERR0004",
        "result.error.detailedDescription": "This task cannot be completed when dependent protection tasks do not complete successfully.",
        "result.error.extendedReason": null,
        "result.error.reason": "Task Performing data rollover for the slices created was skipped because the protection task was unsuccessful.",
        "result.error.remediation": "Review the details for the protection task in the Jobs window to troubleshoot the issue. When the issue is resolved, retry the protection job task. If the issue persists, contact Dell Customer Support.",
        "asset.name": null,
        "asset.type": "NAS_SHARE",
        "host.name": null,
        "host.type": null,
        "inventorySource.type": null,
        "protectionPolicy.name": "NAS Backups - TEST PLC",
        "protectionPolicy.type": "NAS_SHARE",
        "createTime": "2024-11-14T14:34:08.314Z",
        "endTime": "2024-11-14T14:35:43.201Z"
    },
    {
        "category": "PROTECT",
        "classType": "JOB",
        "result.status": "FAILED",
        "result.error.code": "AERR0019",
        "result.error.detailedDescription": "This task is unsuccessful because internal issue happens at service side.",
        "result.error.extendedReason": null,
        "result.error.reason": "This task is unsuccessful because internal issue happens at service side.",
        "result.error.remediation": "To troubleshoot this issue: wait for some time and then retry the operation again. If the issue persists, contact Dell Customer Support.",
        "asset.name": "Linux0032",
        "asset.type": "VMWARE_VIRTUAL_MACHINE",
        "host.name": null,
        "host.type": null,
        "inventorySource.type": "VCENTER",
        "protectionPolicy.name": "Virtual Machines -Crash consistent -Test PLC",
        "protectionPolicy.type": "VMWARE_VIRTUAL_MACHINE",
        "createTime": "2024-11-14T14:34:22.621Z",
        "endTime": "2024-11-14T14:36:06.494Z"
    },
    {
        "category": "PROTECT",
        "classType": "TASK",
        "result.status": "FAILED",
        "result.error.code": "ABV0026",
        "result.error.detailedDescription": "The VM Direct engine cannot complete the backup of this virtual machine because of a protection storage capacity issue on the PowerProtect DD.",
        "result.error.extendedReason": "Cannot create export directory 'Virtual_Machines_-Crash_consistent_--ppdm-01-ef2c3/PLCTLP-526629ba-5227-4c6f-a26d-0ff368976ef4/Stagings/4c6e8a0d-b323-44bf-b12b-da850be18bc5/50007493-6e6e-926e-1a57-11fa19db6108/1731594962156906635' on 'ddve-01.demo.local':  [5005] No space left on device",
        "result.error.reason": "The VM Direct engine 'localhost' is unable to back up the virtual machine 'Linux0032' on vCenter 'VCenter' because the available space on the protection storage system 'ddve-01.demo.local' is insufficient.",
        "result.error.remediation": "Check the protection storage system to determine if there is enough free space for the operation. The PowerProtect DD Administration Guide provides more information on how to reclaim space.",
        "asset.name": "Linux0032",
        "asset.type": null,
        "host.name": "esxi01-7.demo.local",
        "host.type": null,
        "inventorySource.type": null,
        "protectionPolicy.name": "Virtual Machines -Crash consistent -Test PLC",
        "protectionPolicy.type": null,
        "createTime": "2024-11-14T14:35:57.354Z",
        "endTime": "2024-11-14T14:36:06.044Z"
    },
    {
        "category": "PROTECT",
        "classType": "TASK",
        "result.status": "FAILED",
        "result.error.code": "ABNA0020",
        "result.error.detailedDescription": "The existence of the target asset cannot be validated.",
        "result.error.extendedReason": "NAS vProxy Engine nas-proxy.demo.local is unable to perform SnapshotAndSlice operation for nasShare /ifs/data/csi/k8s-d8196857f7. \n\nError Details:\n TaskId: 0d0dc72a-e091-4a89-90b4-203d710bc79f, JobId 0d0dc72a-e091-4a89-90b4-203d710bc79f \n NAS agent error code 'ABNA0020'. Unable to complete the 'SNAPSHOT_AND_SLICE' operation because the location for asset '/ifs/data/csi/k8s-d8196857f7' could not be validated in PowerScale/Isilon NAS '192.168.1.108'.. \n",
        "result.error.reason": "Unable to complete a SNAPSHOT_AND_SLICE operation because the location for asset /ifs/data/csi/k8s-d8196857f7 could not be validated in PowerScale/Isilon NAS 192.168.1.108.",
        "result.error.remediation": "Connect to the PowerScale/Isilon NAS and verify that the share exists. \nFrom the PowerProtect Data Manager Asset Source page, perform an on-demand discovery of assets from this asset source.",
        "asset.name": null,
        "asset.type": "NAS_SHARE",
        "host.name": null,
        "host.type": null,
        "inventorySource.type": null,
        "protectionPolicy.name": "NAS Backups - TEST PLC",
        "protectionPolicy.type": "NAS_SHARE",
        "createTime": "2024-11-14T14:34:08.484Z",
        "endTime": "2024-11-14T14:37:10.673Z"
    },
    {
        "category": "PROTECT",
        "classType": "TASK",
        "result.status": "SKIPPED",
        "result.error.code": "AERR0004",
        "result.error.detailedDescription": "This task cannot be completed when dependent protection tasks do not complete successfully.",
        "result.error.extendedReason": null,
        "result.error.reason": "Task Performing data rollover for the slices created was skipped because the protection task was unsuccessful.",
        "result.error.remediation": "Review the details for the protection task in the Jobs window to troubleshoot the issue. When the issue is resolved, retry the protection job task. If the issue persists, contact Dell Customer Support.",
        "asset.name": null,
        "asset.type": "NAS_SHARE",
        "host.name": null,
        "host.type": null,
        "inventorySource.type": null,
        "protectionPolicy.name": "NAS Backups - TEST PLC",
        "protectionPolicy.type": "NAS_SHARE",
        "createTime": "2024-11-14T14:34:08.508Z",
        "endTime": "2024-11-14T14:37:10.786Z"
    },
    {
        "category": "PROTECT",
        "classType": "TASK",
        "result.status": "FAILED",
        "result.error.code": "ABNA0013",
        "result.error.detailedDescription": "A stub file cannot be created on the PowerProtect DD System to get a unique transaction ID backup.",
        "result.error.extendedReason": "NAS vProxy Engine nas-proxy.demo.local is unable to perform SnapshotAndSlice operation for nasShare /ifs/nfs-share01. \n\nError Details:\n TaskId: 7d51499e-1bb0-4287-998a-7c4e549362c3, JobId 7d51499e-1bb0-4287-998a-7c4e549362c3 \n NAS agent error code 'ABNA0013'. Unable to create a save set with a timestamp: 1731594995008436989.\n. \n",
        "result.error.reason": "Unable to complete the SNAPSHOT_AND_SLICE operation because a backup copy ID for share /ifs/nfs-share01 could not be generated.",
        "result.error.remediation": "To troubleshoot this issue: \n1) Check for connectivity between the PowerProtect DD system, PowerProtect Data Manager, and the NAS protection engine. \n2) Verify that there is enough storage space on the PowerProtect DD system and that the corresponding Storage Unit (SU) is accessible. \n3) Retry the operation. If the issue persists, contact Dell Customer Support.",
        "asset.name": null,
        "asset.type": "NAS_SHARE",
        "host.name": null,
        "host.type": null,
        "inventorySource.type": null,
        "protectionPolicy.name": "NAS Backups - TEST PLC",
        "protectionPolicy.type": "NAS_SHARE",
        "createTime": "2024-11-14T14:34:08.676Z",
        "endTime": "2024-11-14T14:37:12.653Z"
    },
    {
        "category": "PROTECT",
        "classType": "TASK",
        "result.status": "SKIPPED",
        "result.error.code": "AERR0004",
        "result.error.detailedDescription": "This task cannot be completed when dependent protection tasks do not complete successfully.",
        "result.error.extendedReason": null,
        "result.error.reason": "Task Performing data rollover for the slices created was skipped because the protection task was unsuccessful.",
        "result.error.remediation": "Review the details for the protection task in the Jobs window to troubleshoot the issue. When the issue is resolved, retry the protection job task. If the issue persists, contact Dell Customer Support.",
        "asset.name": null,
        "asset.type": "NAS_SHARE",
        "host.name": null,
        "host.type": null,
        "inventorySource.type": null,
        "protectionPolicy.name": "NAS Backups - TEST PLC",
        "protectionPolicy.type": "NAS_SHARE",
        "createTime": "2024-11-14T14:34:08.704Z",
        "endTime": "2024-11-14T14:37:12.745Z"
    },
    {
        "category": "PROTECT",
        "classType": "JOB",
        "result.status": "FAILED",
        "result.error.code": "ABNA0020",
        "result.error.detailedDescription": "The existence of the target asset cannot be validated.",
        "result.error.extendedReason": "NAS vProxy Engine nas-proxy.demo.local is unable to perform SnapshotAndSlice operation for nasShare /ifs/data/csi/k8s-d8196857f7. \n\nError Details:\n TaskId: 0d0dc72a-e091-4a89-90b4-203d710bc79f, JobId 0d0dc72a-e091-4a89-90b4-203d710bc79f \n NAS agent error code 'ABNA0020'. Unable to complete the 'SNAPSHOT_AND_SLICE' operation because the location for asset '/ifs/data/csi/k8s-d8196857f7' could not be validated in PowerScale/Isilon NAS '192.168.1.108'.. \n",
        "result.error.reason": "Unable to complete a SNAPSHOT_AND_SLICE operation because the location for asset /ifs/data/csi/k8s-d8196857f7 could not be validated in PowerScale/Isilon NAS 192.168.1.108.",
        "result.error.remediation": "Connect to the PowerScale/Isilon NAS and verify that the share exists. \nFrom the PowerProtect Data Manager Asset Source page, perform an on-demand discovery of assets from this asset source.",
        "asset.name": "/ifs/data/csi/k8s-d8196857f7",
        "asset.type": "NAS_SHARE",
        "host.name": null,
        "host.type": null,
        "inventorySource.type": null,
        "protectionPolicy.name": "NAS Backups - TEST PLC",
        "protectionPolicy.type": "NAS_SHARE",
        "createTime": "2024-11-14T14:34:08.459Z",
        "endTime": "2024-11-14T14:37:36.707Z"
    },
    {
        "category": "PROTECT",
        "classType": "JOB",
        "result.status": "FAILED",
        "result.error.code": "ABNA0013",
        "result.error.detailedDescription": "A stub file cannot be created on the PowerProtect DD System to get a unique transaction ID backup.",
        "result.error.extendedReason": "NAS vProxy Engine nas-proxy.demo.local is unable to perform SnapshotAndSlice operation for nasShare /ifs/nfs-share01. \n\nError Details:\n TaskId: 7d51499e-1bb0-4287-998a-7c4e549362c3, JobId 7d51499e-1bb0-4287-998a-7c4e549362c3 \n NAS agent error code 'ABNA0013'. Unable to create a save set with a timestamp: 1731594995008436989.\n. \n",
        "result.error.reason": "Unable to complete the SNAPSHOT_AND_SLICE operation because a backup copy ID for share /ifs/nfs-share01 could not be generated.",
        "result.error.remediation": "To troubleshoot this issue: \n1) Check for connectivity between the PowerProtect DD system, PowerProtect Data Manager, and the NAS protection engine. \n2) Verify that there is enough storage space on the PowerProtect DD system and that the corresponding Storage Unit (SU) is accessible. \n3) Retry the operation. If the issue persists, contact Dell Customer Support.",
        "asset.name": "/ifs/nfs-share01",
        "asset.type": "NAS_SHARE",
        "host.name": null,
        "host.type": null,
        "inventorySource.type": null,
        "protectionPolicy.name": "NAS Backups - TEST PLC",
        "protectionPolicy.type": "NAS_SHARE",
        "createTime": "2024-11-14T14:34:08.651Z",
        "endTime": "2024-11-14T14:37:36.884Z"
    },
    {
        "category": "CONFIG",
        "classType": "TASK",
        "result.status": "FAILED",
        "result.error.code": "ABV0025",
        "result.error.detailedDescription": "The VM Direct engine cannot complete protection of this virtual machine because the protection configuration was unsuccessful.",
        "result.error.extendedReason": "Unable to configure protection for the asset because SCSI sharing and is not supported.",
        "result.error.reason": "VM Direct engine is unable to configure protection for the virtual machine 'win-11' on vCenter 'VCenter'.",
        "result.error.remediation": "Review the error details and summary log in the Jobs window, or export the job logs and review the log files for more information. If the issue persists, contact Dell Customer Support.",
        "asset.name": "win-11",
        "asset.type": null,
        "host.name": null,
        "host.type": null,
        "inventorySource.type": null,
        "protectionPolicy.name": "Virtual Machines -Crash consistent -Test PLC",
        "protectionPolicy.type": null,
        "createTime": "2024-11-14T14:38:01.441Z",
        "endTime": "2024-11-14T14:38:01.848Z"
    },
    {
        "category": "PROTECT",
        "classType": "JOB",
        "result.status": "FAILED",
        "result.error.code": "ABV0025",
        "result.error.detailedDescription": "The VM Direct engine cannot complete protection of this virtual machine because the protection configuration was unsuccessful.",
        "result.error.extendedReason": "Unable to configure protection for the asset because SCSI sharing and is not supported.",
        "result.error.reason": "VM Direct engine is unable to configure protection for the virtual machine 'win-11' on vCenter 'VCenter'.",
        "result.error.remediation": "Review the error details and summary log in the Jobs window, or export the job logs and review the log files for more information. If the issue persists, contact Dell Customer Support.",
        "asset.name": "win-11",
        "asset.type": "VMWARE_VIRTUAL_MACHINE",
        "host.name": null,
        "host.type": null,
        "inventorySource.type": "VCENTER",
        "protectionPolicy.name": "Virtual Machines -Crash consistent -Test PLC",
        "protectionPolicy.type": "VMWARE_VIRTUAL_MACHINE",
        "createTime": "2024-11-14T14:34:26.925Z",
        "endTime": "2024-11-14T14:38:02.303Z"
    },
    {
        "category": "PROTECT",
        "classType": "JOB",
        "result.status": "FAILED",
        "result.error.code": "ABNA0013",
        "result.error.detailedDescription": "A stub file cannot be created on the PowerProtect DD System to get a unique transaction ID backup.",
        "result.error.extendedReason": "NAS vProxy Engine nas-proxy.demo.local is unable to perform SnapshotAndSlice operation for nasShare win-share01. \n\nError Details:\n TaskId: 3b374ef6-4083-4e89-a858-c49a8cc4116c, JobId 3b374ef6-4083-4e89-a858-c49a8cc4116c \n NAS agent error code 'ABNA0013'. Unable to create a save set with a timestamp: 1731595021569093435.\n. \n",
        "result.error.reason": "Unable to complete the SNAPSHOT_AND_SLICE operation because a backup copy ID for share win-share01 could not be generated.",
        "result.error.remediation": "To troubleshoot this issue: \n1) Check for connectivity between the PowerProtect DD system, PowerProtect Data Manager, and the NAS protection engine. \n2) Verify that there is enough storage space on the PowerProtect DD system and that the corresponding Storage Unit (SU) is accessible. \n3) Retry the operation. If the issue persists, contact Dell Customer Support.",
        "asset.name": "win-share01",
        "asset.type": "NAS_SHARE",
        "host.name": null,
        "host.type": null,
        "inventorySource.type": null,
        "protectionPolicy.name": "NAS Backups - TEST PLC",
        "protectionPolicy.type": "NAS_SHARE",
        "createTime": "2024-11-14T14:34:08.848Z",
        "endTime": "2024-11-14T14:38:07.222Z"
    },
    {
        "category": "PROTECT",
        "classType": "JOB",
        "result.status": "FAILED",
        "result.error.code": "ABA0002",
        "result.error.detailedDescription": "The protection policy backup was unsuccessful because of an agent issue.",
        "result.error.extendedReason": "Protection policy backup was unsuccessful because the Agent failed with the following error: SQLite database initialization failed.",
        "result.error.reason": "Filesystem Backups -TEST PLC: Unable to backup FILE_SYSTEM asset DISASTER_RECOVERY:\\ on host win-10.demo.local to storage target Filesystem_Backups_-TEST_PLC-ppdm-01-b89b3 because of an agent issue.",
        "result.error.remediation": "Click export log and review the log file to determine the status of the job or check agent logs for more details.",
        "asset.name": "DISASTER_RECOVERY:\\",
        "asset.type": "FILE_SYSTEM",
        "host.name": "win-10.demo.local",
        "host.type": "APP_HOST",
        "inventorySource.type": null,
        "protectionPolicy.name": "Filesystem Backups -TEST PLC",
        "protectionPolicy.type": "FILE_SYSTEM",
        "createTime": "2024-11-14T14:33:57.781Z",
        "endTime": "2024-11-14T14:45:01.661Z"
    },
    {
        "category": "PROTECT",
        "classType": "TASK",
        "result.status": "FAILED",
        "result.error.code": "ABA0002",
        "result.error.detailedDescription": "The protection policy backup was unsuccessful because of an agent issue.",
        "result.error.extendedReason": "Protection policy backup was unsuccessful because the Agent failed with the following error: SQLite database initialization failed.",
        "result.error.reason": "Filesystem Backups -TEST PLC: Unable to backup FILE_SYSTEM asset DISASTER_RECOVERY:\\ on host win-10.demo.local to storage target Filesystem_Backups_-TEST_PLC-ppdm-01-b89b3 because of an agent issue.",
        "result.error.remediation": "Click export log and review the log file to determine the status of the job or check agent logs for more details.",
        "asset.name": "DISASTER_RECOVERY:\\",
        "asset.type": null,
        "host.name": "win-10.demo.local",
        "host.type": null,
        "inventorySource.type": null,
        "protectionPolicy.name": "Filesystem Backups -TEST PLC",
        "protectionPolicy.type": null,
        "createTime": "2024-11-14T14:34:18.797Z",
        "endTime": "2024-11-14T14:45:01.286Z"
    },
    {
        "category": "PROTECT",
        "classType": "JOB",
        "result.status": "FAILED",
        "result.error.code": "ABA0002",
        "result.error.detailedDescription": "The protection policy backup was unsuccessful because of an agent issue.",
        "result.error.extendedReason": "Protection policy backup was unsuccessful because the Agent failed with the following error: SQLite database initialization failed.",
        "result.error.reason": "Filesystem Backups -TEST PLC: Unable to backup FILE_SYSTEM asset C:\\ on host win-01.demo.local to storage target Filesystem_Backups_-TEST_PLC-ppdm-01-b89b3 because of an agent issue.",
        "result.error.remediation": "Click export log and review the log file to determine the status of the job or check agent logs for more details.",
        "asset.name": "C:\\",
        "asset.type": "FILE_SYSTEM",
        "host.name": "win-01.demo.local",
        "host.type": "APP_HOST",
        "inventorySource.type": null,
        "protectionPolicy.name": "Filesystem Backups -TEST PLC",
        "protectionPolicy.type": "FILE_SYSTEM",
        "createTime": "2024-11-14T14:33:58.461Z",
        "endTime": "2024-11-14T14:45:02.065Z"
    },
    {
        "category": "PROTECT",
        "classType": "JOB",
        "result.status": "FAILED",
        "result.error.code": "ABA0002",
        "result.error.detailedDescription": "The protection policy backup was unsuccessful because of an agent issue.",
        "result.error.extendedReason": "Protection policy backup was unsuccessful because the Agent failed with the following error: SQLite database initialization failed.",
        "result.error.reason": "Filesystem Backups -TEST PLC: Unable to backup FILE_SYSTEM asset E:\\ on host win-01.demo.local to storage target Filesystem_Backups_-TEST_PLC-ppdm-01-b89b3 because of an agent issue.",
        "result.error.remediation": "Click export log and review the log file to determine the status of the job or check agent logs for more details.",
        "asset.name": "E:\\",
        "asset.type": "FILE_SYSTEM",
        "host.name": "win-01.demo.local",
        "host.type": "APP_HOST",
        "inventorySource.type": null,
        "protectionPolicy.name": "Filesystem Backups -TEST PLC",
        "protectionPolicy.type": "FILE_SYSTEM",
        "createTime": "2024-11-14T14:33:57.076Z",
        "endTime": "2024-11-14T14:45:02.069Z"
    },
    {
        "category": "PROTECT",
        "classType": "TASK",
        "result.status": "FAILED",
        "result.error.code": "ABA0002",
        "result.error.detailedDescription": "The protection policy backup was unsuccessful because of an agent issue.",
        "result.error.extendedReason": "Protection policy backup was unsuccessful because the Agent failed with the following error: SQLite database initialization failed.",
        "result.error.reason": "Filesystem Backups -TEST PLC: Unable to backup FILE_SYSTEM asset C:\\ on host win-01.demo.local to storage target Filesystem_Backups_-TEST_PLC-ppdm-01-b89b3 because of an agent issue.",
        "result.error.remediation": "Click export log and review the log file to determine the status of the job or check agent logs for more details.",
        "asset.name": "C:\\",
        "asset.type": null,
        "host.name": "win-01.demo.local",
        "host.type": null,
        "inventorySource.type": null,
        "protectionPolicy.name": "Filesystem Backups -TEST PLC",
        "protectionPolicy.type": null,
        "createTime": "2024-11-14T14:34:18.800Z",
        "endTime": "2024-11-14T14:45:01.680Z"
    },
    {
        "category": "PROTECT",
        "classType": "TASK",
        "result.status": "FAILED",
        "result.error.code": "ABA0002",
        "result.error.detailedDescription": "The protection policy backup was unsuccessful because of an agent issue.",
        "result.error.extendedReason": "Protection policy backup was unsuccessful because the Agent failed with the following error: SQLite database initialization failed.",
        "result.error.reason": "Filesystem Backups -TEST PLC: Unable to backup FILE_SYSTEM asset E:\\ on host win-01.demo.local to storage target Filesystem_Backups_-TEST_PLC-ppdm-01-b89b3 because of an agent issue.",
        "result.error.remediation": "Click export log and review the log file to determine the status of the job or check agent logs for more details.",
        "asset.name": "E:\\",
        "asset.type": null,
        "host.name": "win-01.demo.local",
        "host.type": null,
        "inventorySource.type": null,
        "protectionPolicy.name": "Filesystem Backups -TEST PLC",
        "protectionPolicy.type": null,
        "createTime": "2024-11-14T14:34:18.963Z",
        "endTime": "2024-11-14T14:45:01.657Z"
    },
    {
        "category": "PROTECT",
        "classType": "TASK",
        "result.status": "UNKNOWN",
        "result.error.code": "ABA0023",
        "result.error.detailedDescription": "Monitoring of this session cannot be completed because of an unknown error occurred during monitoring.",
        "result.error.extendedReason": "",
        "result.error.reason": "Exchange Backups - TEST PLC: Unable to monitor backup/restore session of MICROSOFT_EXCHANGE_DATABASE asset Test_DB_001 in host exchange.demo.local because of an unknown error. The backup/restore session might be running on the client.",
        "result.error.remediation": "Monitor the next few jobs and please ensure network connectivity between agent and PowerProtect Data Manager has no issues and all the services of PowerProtect Data Manager are up and running.",
        "asset.name": "Test_DB_001",
        "asset.type": null,
        "host.name": "exchange.demo.local",
        "host.type": null,
        "inventorySource.type": null,
        "protectionPolicy.name": "Exchange Backups - TEST PLC",
        "protectionPolicy.type": null,
        "createTime": "2024-11-14T14:34:18.802Z",
        "endTime": "2024-11-14T14:34:29.716Z"
    },
    {
        "category": "PROTECT",
        "classType": "TASK",
        "result.status": "UNKNOWN",
        "result.error.code": "ABA0023",
        "result.error.detailedDescription": "Monitoring of this session cannot be completed because of an unknown error occurred during monitoring.",
        "result.error.extendedReason": "",
        "result.error.reason": "Exchange Backups - TEST PLC: Unable to monitor backup/restore session of MICROSOFT_EXCHANGE_DATABASE asset Test_DB_003 in host exchange.demo.local because of an unknown error. The backup/restore session might be running on the client.",
        "result.error.remediation": "Monitor the next few jobs and please ensure network connectivity between agent and PowerProtect Data Manager has no issues and all the services of PowerProtect Data Manager are up and running.",
        "asset.name": "Test_DB_003",
        "asset.type": null,
        "host.name": "exchange.demo.local",
        "host.type": null,
        "inventorySource.type": null,
        "protectionPolicy.name": "Exchange Backups - TEST PLC",
        "protectionPolicy.type": null,
        "createTime": "2024-11-14T14:34:18.953Z",
        "endTime": "2024-11-14T14:34:29.762Z"
    },
    {
        "category": "PROTECT",
        "classType": "TASK",
        "result.status": "UNKNOWN",
        "result.error.code": "ABA0023",
        "result.error.detailedDescription": "Monitoring of this session cannot be completed because of an unknown error occurred during monitoring.",
        "result.error.extendedReason": "",
        "result.error.reason": "Exchange Backups - TEST PLC: Unable to monitor backup/restore session of MICROSOFT_EXCHANGE_DATABASE asset Mailbox Database 0597205983 in host exchange.demo.local because of an unknown error. The backup/restore session might be running on the client.",
        "result.error.remediation": "Monitor the next few jobs and please ensure network connectivity between agent and PowerProtect Data Manager has no issues and all the services of PowerProtect Data Manager are up and running.",
        "asset.name": "Mailbox Database 0597205983",
        "asset.type": null,
        "host.name": "exchange.demo.local",
        "host.type": null,
        "inventorySource.type": null,
        "protectionPolicy.name": "Exchange Backups - TEST PLC",
        "protectionPolicy.type": null,
        "createTime": "2024-11-14T14:34:18.815Z",
        "endTime": "2024-11-14T14:34:29.772Z"
    },
    {
        "category": "PROTECT",
        "classType": "TASK",
        "result.status": "UNKNOWN",
        "result.error.code": "ABA0023",
        "result.error.detailedDescription": "Monitoring of this session cannot be completed because of an unknown error occurred during monitoring.",
        "result.error.extendedReason": "",
        "result.error.reason": "Exchange Backups - TEST PLC: Unable to monitor backup/restore session of MICROSOFT_EXCHANGE_DATABASE asset Test_DB_002 in host exchange.demo.local because of an unknown error. The backup/restore session might be running on the client.",
        "result.error.remediation": "Monitor the next few jobs and please ensure network connectivity between agent and PowerProtect Data Manager has no issues and all the services of PowerProtect Data Manager are up and running.",
        "asset.name": "Test_DB_002",
        "asset.type": null,
        "host.name": "exchange.demo.local",
        "host.type": null,
        "inventorySource.type": null,
        "protectionPolicy.name": "Exchange Backups - TEST PLC",
        "protectionPolicy.type": null,
        "createTime": "2024-11-14T14:34:18.800Z",
        "endTime": "2024-11-14T14:34:29.797Z"
    },
    {
        "category": "PROTECT",
        "classType": "TASK",
        "result.status": "UNKNOWN",
        "result.error.code": "ABA0023",
        "result.error.detailedDescription": "Monitoring of this session cannot be completed because of an unknown error occurred during monitoring.",
        "result.error.extendedReason": "",
        "result.error.reason": "Exchange Backups - TEST PLC: Unable to monitor backup/restore session of MICROSOFT_EXCHANGE_DATABASE asset Test_DB_004 in host exchange.demo.local because of an unknown error. The backup/restore session might be running on the client.",
        "result.error.remediation": "Monitor the next few jobs and please ensure network connectivity between agent and PowerProtect Data Manager has no issues and all the services of PowerProtect Data Manager are up and running.",
        "asset.name": "Test_DB_004",
        "asset.type": null,
        "host.name": "exchange.demo.local",
        "host.type": null,
        "inventorySource.type": null,
        "protectionPolicy.name": "Exchange Backups - TEST PLC",
        "protectionPolicy.type": null,
        "createTime": "2024-11-14T14:34:18.931Z",
        "endTime": "2024-11-14T14:34:29.813Z"
    },
    {
        "category": "PROTECT",
        "classType": "JOB",
        "result.status": "UNKNOWN",
        "result.error.code": "ABA0023",
        "result.error.detailedDescription": "Monitoring of this session cannot be completed because of an unknown error occurred during monitoring.",
        "result.error.extendedReason": "",
        "result.error.reason": "Exchange Backups - TEST PLC: Unable to monitor backup/restore session of MICROSOFT_EXCHANGE_DATABASE asset Test_DB_004 in host exchange.demo.local because of an unknown error. The backup/restore session might be running on the client.",
        "result.error.remediation": "Monitor the next few jobs and please ensure network connectivity between agent and PowerProtect Data Manager has no issues and all the services of PowerProtect Data Manager are up and running.",
        "asset.name": "Test_DB_004",
        "asset.type": "MICROSOFT_EXCHANGE_DATABASE",
        "host.name": "exchange.demo.local",
        "host.type": "APP_HOST",
        "inventorySource.type": null,
        "protectionPolicy.name": "Exchange Backups - TEST PLC",
        "protectionPolicy.type": "MICROSOFT_EXCHANGE_DATABASE",
        "createTime": "2024-11-14T14:33:53.605Z",
        "endTime": "2024-11-14T14:34:30.508Z"
    },
    {
        "category": "PROTECT",
        "classType": "JOB",
        "result.status": "UNKNOWN",
        "result.error.code": "ABA0023",
        "result.error.detailedDescription": "Monitoring of this session cannot be completed because of an unknown error occurred during monitoring.",
        "result.error.extendedReason": "",
        "result.error.reason": "Exchange Backups - TEST PLC: Unable to monitor backup/restore session of MICROSOFT_EXCHANGE_DATABASE asset Test_DB_002 in host exchange.demo.local because of an unknown error. The backup/restore session might be running on the client.",
        "result.error.remediation": "Monitor the next few jobs and please ensure network connectivity between agent and PowerProtect Data Manager has no issues and all the services of PowerProtect Data Manager are up and running.",
        "asset.name": "Test_DB_002",
        "asset.type": "MICROSOFT_EXCHANGE_DATABASE",
        "host.name": "exchange.demo.local",
        "host.type": "APP_HOST",
        "inventorySource.type": null,
        "protectionPolicy.name": "Exchange Backups - TEST PLC",
        "protectionPolicy.type": "MICROSOFT_EXCHANGE_DATABASE",
        "createTime": "2024-11-14T14:33:52.947Z",
        "endTime": "2024-11-14T14:34:30.730Z"
    },
    {
        "category": "PROTECT",
        "classType": "JOB",
        "result.status": "UNKNOWN",
        "result.error.code": "ABA0023",
        "result.error.detailedDescription": "Monitoring of this session cannot be completed because of an unknown error occurred during monitoring.",
        "result.error.extendedReason": "",
        "result.error.reason": "Exchange Backups - TEST PLC: Unable to monitor backup/restore session of MICROSOFT_EXCHANGE_DATABASE asset Mailbox Database 0597205983 in host exchange.demo.local because of an unknown error. The backup/restore session might be running on the client.",
        "result.error.remediation": "Monitor the next few jobs and please ensure network connectivity between agent and PowerProtect Data Manager has no issues and all the services of PowerProtect Data Manager are up and running.",
        "asset.name": "Mailbox Database 0597205983",
        "asset.type": "MICROSOFT_EXCHANGE_DATABASE",
        "host.name": "exchange.demo.local",
        "host.type": "APP_HOST",
        "inventorySource.type": null,
        "protectionPolicy.name": "Exchange Backups - TEST PLC",
        "protectionPolicy.type": "MICROSOFT_EXCHANGE_DATABASE",
        "createTime": "2024-11-14T14:33:52.753Z",
        "endTime": "2024-11-14T14:34:30.958Z"
    },
    {
        "category": "PROTECT",
        "classType": "JOB",
        "result.status": "UNKNOWN",
        "result.error.code": "ABA0023",
        "result.error.detailedDescription": "Monitoring of this session cannot be completed because of an unknown error occurred during monitoring.",
        "result.error.extendedReason": "",
        "result.error.reason": "Exchange Backups - TEST PLC: Unable to monitor backup/restore session of MICROSOFT_EXCHANGE_DATABASE asset Test_DB_003 in host exchange.demo.local because of an unknown error. The backup/restore session might be running on the client.",
        "result.error.remediation": "Monitor the next few jobs and please ensure network connectivity between agent and PowerProtect Data Manager has no issues and all the services of PowerProtect Data Manager are up and running.",
        "asset.name": "Test_DB_003",
        "asset.type": "MICROSOFT_EXCHANGE_DATABASE",
        "host.name": "exchange.demo.local",
        "host.type": "APP_HOST",
        "inventorySource.type": null,
        "protectionPolicy.name": "Exchange Backups - TEST PLC",
        "protectionPolicy.type": "MICROSOFT_EXCHANGE_DATABASE",
        "createTime": "2024-11-14T14:33:53.428Z",
        "endTime": "2024-11-14T14:34:31.234Z"
    },
    {
        "category": "PROTECT",
        "classType": "JOB",
        "result.status": "UNKNOWN",
        "result.error.code": "ABA0023",
        "result.error.detailedDescription": "Monitoring of this session cannot be completed because of an unknown error occurred during monitoring.",
        "result.error.extendedReason": "",
        "result.error.reason": "Exchange Backups - TEST PLC: Unable to monitor backup/restore session of MICROSOFT_EXCHANGE_DATABASE asset Test_DB_001 in host exchange.demo.local because of an unknown error. The backup/restore session might be running on the client.",
        "result.error.remediation": "Monitor the next few jobs and please ensure network connectivity between agent and PowerProtect Data Manager has no issues and all the services of PowerProtect Data Manager are up and running.",
        "asset.name": "Test_DB_001",
        "asset.type": "MICROSOFT_EXCHANGE_DATABASE",
        "host.name": "exchange.demo.local",
        "host.type": "APP_HOST",
        "inventorySource.type": null,
        "protectionPolicy.name": "Exchange Backups - TEST PLC",
        "protectionPolicy.type": "MICROSOFT_EXCHANGE_DATABASE",
        "createTime": "2024-11-14T14:33:53.135Z",
        "endTime": "2024-11-14T14:34:31.466Z"
    },
    {
        "category": "PROTECT",
        "classType": "JOB",
        "result.status": "FAILED",
        "result.error.code": "ABK0018",
        "result.error.detailedDescription": "The backup of this Kubernetes namespace was not successful because of a problem on the protection storage.",
        "result.error.extendedReason": "Unable to setup backup.  Unable to create directory 'Kubernetes_Backups_-_TEST_PLC-ppdm-01-a2e89/PLCTLP-694fb9a3-e763-4352-8b08-e0b323f863f0/Stagings/e6e4041f-3e15-47bf-b03c-9128d568a63c/vmware-system-csi/1731594892213643903':  [5005] No space left on device",
        "result.error.reason": "Unable to back up namespace 'vmware-system-csi' in Kubernetes cluster 'Cluster-01' because of a protection storage issue.",
        "result.error.remediation": "Verify that the PowerProtect DD System is fully functional and that the DD Boost ports are open between the Kubernetes cluster and the PowerProtect DD System.",
        "asset.name": "vmware-system-csi",
        "asset.type": "KUBERNETES",
        "host.name": null,
        "host.type": null,
        "inventorySource.type": "KUBERNETES",
        "protectionPolicy.name": "Kubernetes Backups - TEST PLC",
        "protectionPolicy.type": "KUBERNETES",
        "createTime": "2024-11-14T14:34:03.167Z",
        "endTime": "2024-11-14T14:34:51.257Z"
    },
    {
        "category": "PROTECT",
        "classType": "JOB",
        "result.status": "FAILED",
        "result.error.code": "ABK0018",
        "result.error.detailedDescription": "The backup of this Kubernetes namespace was not successful because of a problem on the protection storage.",
        "result.error.extendedReason": "Unable to setup backup.  Unable to create directory 'Kubernetes_Backups_-_TEST_PLC-ppdm-01-a2e89/PLCTLP-694fb9a3-e763-4352-8b08-e0b323f863f0/Stagings/e6e4041f-3e15-47bf-b03c-9128d568a63c/mysql/1731594897013233316':  [5005] No space left on device",
        "result.error.reason": "Unable to back up namespace 'mysql' in Kubernetes cluster 'Cluster-01' because of a protection storage issue.",
        "result.error.remediation": "Verify that the PowerProtect DD System is fully functional and that the DD Boost ports are open between the Kubernetes cluster and the PowerProtect DD System.",
        "asset.name": "mysql",
        "asset.type": "KUBERNETES",
        "host.name": null,
        "host.type": null,
        "inventorySource.type": "KUBERNETES",
        "protectionPolicy.name": "Kubernetes Backups - TEST PLC",
        "protectionPolicy.type": "KUBERNETES",
        "createTime": "2024-11-14T14:34:03.046Z",
        "endTime": "2024-11-14T14:34:50.981Z"
    },
    {
        "category": "PROTECT",
        "classType": "JOB",
        "result.status": "FAILED",
        "result.error.code": "ABK0018",
        "result.error.detailedDescription": "The backup of this Kubernetes namespace was not successful because of a problem on the protection storage.",
        "result.error.extendedReason": "Unable to setup backup.  Unable to create directory 'Kubernetes_Backups_-_TEST_PLC-ppdm-01-a2e89/PLCTLP-694fb9a3-e763-4352-8b08-e0b323f863f0/Stagings/e6e4041f-3e15-47bf-b03c-9128d568a63c/isilon/1731594899213259241':  [5005] No space left on device",
        "result.error.reason": "Unable to back up namespace 'isilon' in Kubernetes cluster 'Cluster-01' because of a protection storage issue.",
        "result.error.remediation": "Verify that the PowerProtect DD System is fully functional and that the DD Boost ports are open between the Kubernetes cluster and the PowerProtect DD System.",
        "asset.name": "isilon",
        "asset.type": "KUBERNETES",
        "host.name": null,
        "host.type": null,
        "inventorySource.type": "KUBERNETES",
        "protectionPolicy.name": "Kubernetes Backups - TEST PLC",
        "protectionPolicy.type": "KUBERNETES",
        "createTime": "2024-11-14T14:34:02.717Z",
        "endTime": "2024-11-14T14:34:52.762Z"
    },
    {
        "category": "PROTECT",
        "classType": "TASK",
        "result.status": "FAILED",
        "result.error.code": "ABA0002",
        "result.error.detailedDescription": "The protection policy backup was unsuccessful because of an agent issue.",
        "result.error.extendedReason": "Protection policy backup was unsuccessful because the Agent failed with the following error: Backup of database on host and instance is unsuccessful because of an internal server error. Check the ddbmsqlsv logs available in MSAPPAGENT logs directory on the host for more details.",
        "result.error.reason": "SQL Backups -TEST PLC: Unable to backup MICROSOFT_SQL_DATABASE asset master on host sqlaag-01.demo.local to storage target SQL_Backups_-TEST_PLC-ppdm-01-f0af0 because of an agent issue.",
        "result.error.remediation": "Click export log and review the log file to determine the status of the job or check agent logs for more details.",
        "asset.name": "master",
        "asset.type": null,
        "host.name": "sqlaag-01.demo.local",
        "host.type": null,
        "inventorySource.type": null,
        "protectionPolicy.name": "SQL Backups -TEST PLC",
        "protectionPolicy.type": null,
        "createTime": "2024-11-14T14:34:18.932Z",
        "endTime": "2024-11-14T14:35:02.640Z"
    },
    {
        "category": "PROTECT",
        "classType": "JOB",
        "result.status": "FAILED",
        "result.error.code": "ABA0002",
        "result.error.detailedDescription": "The protection policy backup was unsuccessful because of an agent issue.",
        "result.error.extendedReason": "Protection policy backup was unsuccessful because the Agent failed with the following error: Backup of database on host and instance is unsuccessful because of an internal server error. Check the ddbmsqlsv logs available in MSAPPAGENT logs directory on the host for more details.",
        "result.error.reason": "SQL Backups -TEST PLC: Unable to backup MICROSOFT_SQL_DATABASE asset model on host sqlaag-01.demo.local to storage target SQL_Backups_-TEST_PLC-ppdm-01-f0af0 because of an agent issue.",
        "result.error.remediation": "Click export log and review the log file to determine the status of the job or check agent logs for more details.",
        "asset.name": "model",
        "asset.type": "MICROSOFT_SQL_DATABASE",
        "host.name": "sqlaag-01.demo.local",
        "host.type": "APP_HOST",
        "inventorySource.type": null,
        "protectionPolicy.name": "SQL Backups -TEST PLC",
        "protectionPolicy.type": "MICROSOFT_SQL_DATABASE",
        "createTime": "2024-11-14T14:34:15.467Z",
        "endTime": "2024-11-14T14:35:03.578Z"
    },
    {
        "category": "PROTECT",
        "classType": "JOB",
        "result.status": "FAILED",
        "result.error.code": "ABA0002",
        "result.error.detailedDescription": "The protection policy backup was unsuccessful because of an agent issue.",
        "result.error.extendedReason": "Protection policy backup was unsuccessful because the Agent failed with the following error: Backup of database on host and instance is unsuccessful because of an internal server error. Check the ddbmsqlsv logs available in MSAPPAGENT logs directory on the host for more details.",
        "result.error.reason": "SQL Backups -TEST PLC: Unable to backup MICROSOFT_SQL_DATABASE asset master on host sqlaag-01.demo.local to storage target SQL_Backups_-TEST_PLC-ppdm-01-f0af0 because of an agent issue.",
        "result.error.remediation": "Click export log and review the log file to determine the status of the job or check agent logs for more details.",
        "asset.name": "master",
        "asset.type": "MICROSOFT_SQL_DATABASE",
        "host.name": "sqlaag-01.demo.local",
        "host.type": "APP_HOST",
        "inventorySource.type": null,
        "protectionPolicy.name": "SQL Backups -TEST PLC",
        "protectionPolicy.type": "MICROSOFT_SQL_DATABASE",
        "createTime": "2024-11-14T14:34:16.687Z",
        "endTime": "2024-11-14T14:35:03.448Z"
    },
    {
        "category": "PROTECT",
        "classType": "TASK",
        "result.status": "FAILED",
        "result.error.code": "ABV0026",
        "result.error.detailedDescription": "The VM Direct engine cannot complete the backup of this virtual machine because of a protection storage capacity issue on the PowerProtect DD.",
        "result.error.extendedReason": "Cannot create export directory 'Virtual_Machines_-Crash_consistent_--ppdm-01-ef2c3/PLCTLP-526629ba-5227-4c6f-a26d-0ff368976ef4/Stagings/4c6e8a0d-b323-44bf-b12b-da850be18bc5/50000322-fb7b-d1bb-c5c5-4c1e1a1de9d2/1731594899908609267' on 'ddve-01.demo.local':  [5005] No space left on device",
        "result.error.reason": "The VM Direct engine 'localhost' is unable to back up the virtual machine 'SQL-03' on vCenter 'VCenter' because the available space on the protection storage system 'ddve-01.demo.local' is insufficient.",
        "result.error.remediation": "Check the protection storage system to determine if there is enough free space for the operation. The PowerProtect DD Administration Guide provides more information on how to reclaim space.",
        "asset.name": "SQL-03",
        "asset.type": null,
        "host.name": "esxi03-7.demo.local",
        "host.type": null,
        "inventorySource.type": null,
        "protectionPolicy.name": "Virtual Machines -Crash consistent -Test PLC",
        "protectionPolicy.type": null,
        "createTime": "2024-11-14T14:34:53.212Z",
        "endTime": "2024-11-14T14:35:03.896Z"
    },
    {
        "category": "PROTECT",
        "classType": "TASK",
        "result.status": "FAILED",
        "result.error.code": "ABV0026",
        "result.error.detailedDescription": "The VM Direct engine cannot complete the backup of this virtual machine because of a protection storage capacity issue on the PowerProtect DD.",
        "result.error.extendedReason": "Cannot create export directory 'Virtual_Machines_-Crash_consistent_--ppdm-01-ef2c3/PLCTLP-526629ba-5227-4c6f-a26d-0ff368976ef4/Stagings/4c6e8a0d-b323-44bf-b12b-da850be18bc5/501f6f2d-3c47-e607-dbb3-1476169035a7/1731594899959693456' on 'ddve-01.demo.local':  [5005] No space left on device",
        "result.error.reason": "The VM Direct engine 'localhost' is unable to back up the virtual machine 'sqlaag-01' on vCenter 'VCenter' because the available space on the protection storage system 'ddve-01.demo.local' is insufficient.",
        "result.error.remediation": "Check the protection storage system to determine if there is enough free space for the operation. The PowerProtect DD Administration Guide provides more information on how to reclaim space.",
        "asset.name": "sqlaag-01",
        "asset.type": null,
        "host.name": "esxi03-7.demo.local",
        "host.type": null,
        "inventorySource.type": null,
        "protectionPolicy.name": "Virtual Machines -Crash consistent -Test PLC",
        "protectionPolicy.type": null,
        "createTime": "2024-11-14T14:34:53.203Z",
        "endTime": "2024-11-14T14:35:03.961Z"
    },
    {
        "category": "PROTECT",
        "classType": "TASK",
        "result.status": "FAILED",
        "result.error.code": "ABV0026",
        "result.error.detailedDescription": "The VM Direct engine cannot complete the backup of this virtual machine because of a protection storage capacity issue on the PowerProtect DD.",
        "result.error.extendedReason": "Cannot create export directory 'Virtual_Machines_-Crash_consistent_--ppdm-01-ef2c3/PLCTLP-526629ba-5227-4c6f-a26d-0ff368976ef4/Stagings/4c6e8a0d-b323-44bf-b12b-da850be18bc5/50139ae6-8079-5090-cda7-5591eb2a2032/1731594899933104972' on 'ddve-01.demo.local':  [5005] No space left on device",
        "result.error.reason": "The VM Direct engine 'localhost' is unable to back up the virtual machine 'Isilon' on vCenter 'VCenter' because the available space on the protection storage system 'ddve-01.demo.local' is insufficient.",
        "result.error.remediation": "Check the protection storage system to determine if there is enough free space for the operation. The PowerProtect DD Administration Guide provides more information on how to reclaim space.",
        "asset.name": "Isilon",
        "asset.type": null,
        "host.name": "esxi03-7.demo.local",
        "host.type": null,
        "inventorySource.type": null,
        "protectionPolicy.name": "Virtual Machines -Crash consistent -Test PLC",
        "protectionPolicy.type": null,
        "createTime": "2024-11-14T14:34:53.226Z",
        "endTime": "2024-11-14T14:35:03.980Z"
    },
    {
        "category": "PROTECT",
        "classType": "JOB",
        "result.status": "FAILED",
        "result.error.code": "ABK0018",
        "result.error.detailedDescription": "The backup of this Kubernetes namespace was not successful because of a problem on the protection storage.",
        "result.error.extendedReason": "Unable to setup backup.  Unable to create directory 'Kubernetes_Backups_-_TEST_PLC-ppdm-01-a2e89/PLCTLP-694fb9a3-e763-4352-8b08-e0b323f863f0/Stagings/e6e4041f-3e15-47bf-b03c-9128d568a63c/postgres/1731594920866188229':  [5005] No space left on device",
        "result.error.reason": "Unable to back up namespace 'postgres' in Kubernetes cluster 'Cluster-01' because of a protection storage issue.",
        "result.error.remediation": "Verify that the PowerProtect DD System is fully functional and that the DD Boost ports are open between the Kubernetes cluster and the PowerProtect DD System.",
        "asset.name": "postgres",
        "asset.type": "KUBERNETES",
        "host.name": null,
        "host.type": null,
        "inventorySource.type": "KUBERNETES",
        "protectionPolicy.name": "Kubernetes Backups - TEST PLC",
        "protectionPolicy.type": "KUBERNETES",
        "createTime": "2024-11-14T14:34:03.449Z",
        "endTime": "2024-11-14T14:35:17.159Z"
    },
    {
        "category": "PROTECT",
        "classType": "TASK",
        "result.status": "FAILED",
        "result.error.code": "ABA0002",
        "result.error.detailedDescription": "The protection policy backup was unsuccessful because of an agent issue.",
        "result.error.extendedReason": "Protection policy backup was unsuccessful because the Agent failed with the following error: Backup of database on host and instance is unsuccessful because of an internal server error. Check the ddbmsqlsv logs available in MSAPPAGENT logs directory on the host for more details.",
        "result.error.reason": "SQL Backups -TEST PLC: Unable to backup MICROSOFT_SQL_DATABASE asset master on host sqlaag-02.demo.local to storage target SQL_Backups_-TEST_PLC-ppdm-01-f0af0 because of an agent issue.",
        "result.error.remediation": "Click export log and review the log file to determine the status of the job or check agent logs for more details.",
        "asset.name": "master",
        "asset.type": null,
        "host.name": "sqlaag-02.demo.local",
        "host.type": null,
        "inventorySource.type": null,
        "protectionPolicy.name": "SQL Backups -TEST PLC",
        "protectionPolicy.type": null,
        "createTime": "2024-11-14T14:34:18.800Z",
        "endTime": "2024-11-14T14:35:31.280Z"
    },
    {
        "category": "PROTECT",
        "classType": "JOB",
        "result.status": "FAILED",
        "result.error.code": "ABA0002",
        "result.error.detailedDescription": "The protection policy backup was unsuccessful because of an agent issue.",
        "result.error.extendedReason": "Protection policy backup was unsuccessful because the Agent failed with the following error: Backup of database on host and instance is unsuccessful because of an internal server error. Check the ddbmsqlsv logs available in MSAPPAGENT logs directory on the host for more details.",
        "result.error.reason": "SQL Backups -TEST PLC: Unable to backup MICROSOFT_SQL_DATABASE asset model on host sqlaag-02.demo.local to storage target SQL_Backups_-TEST_PLC-ppdm-01-f0af0 because of an agent issue.",
        "result.error.remediation": "Click export log and review the log file to determine the status of the job or check agent logs for more details.",
        "asset.name": "model",
        "asset.type": "MICROSOFT_SQL_DATABASE",
        "host.name": "sqlaag-02.demo.local",
        "host.type": "APP_HOST",
        "inventorySource.type": null,
        "protectionPolicy.name": "SQL Backups -TEST PLC",
        "protectionPolicy.type": "MICROSOFT_SQL_DATABASE",
        "createTime": "2024-11-14T14:34:15.800Z",
        "endTime": "2024-11-14T14:35:32.365Z"
    },
    {
        "category": "PROTECT",
        "classType": "JOB",
        "result.status": "FAILED",
        "result.error.code": "ABA0002",
        "result.error.detailedDescription": "The protection policy backup was unsuccessful because of an agent issue.",
        "result.error.extendedReason": "Protection policy backup was unsuccessful because the Agent failed with the following error: Backup of database on host and instance is unsuccessful because of an internal server error. Check the ddbmsqlsv logs available in MSAPPAGENT logs directory on the host for more details.",
        "result.error.reason": "SQL Backups -TEST PLC: Unable to backup MICROSOFT_SQL_DATABASE asset master on host sqlaag-02.demo.local to storage target SQL_Backups_-TEST_PLC-ppdm-01-f0af0 because of an agent issue.",
        "result.error.remediation": "Click export log and review the log file to determine the status of the job or check agent logs for more details.",
        "asset.name": "master",
        "asset.type": "MICROSOFT_SQL_DATABASE",
        "host.name": "sqlaag-02.demo.local",
        "host.type": "APP_HOST",
        "inventorySource.type": null,
        "protectionPolicy.name": "SQL Backups -TEST PLC",
        "protectionPolicy.type": "MICROSOFT_SQL_DATABASE",
        "createTime": "2024-11-14T14:34:16.863Z",
        "endTime": "2024-11-14T14:35:32.149Z"
    },
    {
        "category": "PROTECT",
        "classType": "TASK",
        "result.status": "FAILED",
        "result.error.code": "ABV0026",
        "result.error.detailedDescription": "The VM Direct engine cannot complete the backup of this virtual machine because of a protection storage capacity issue on the PowerProtect DD.",
        "result.error.extendedReason": "Cannot create export directory 'Virtual_Machines_-Crash_consistent_--ppdm-01-ef2c3/PLCTLP-526629ba-5227-4c6f-a26d-0ff368976ef4/Stagings/4c6e8a0d-b323-44bf-b12b-da850be18bc5/502f3a1b-c525-c168-d635-458eb6542c7e/1731594928084810016' on 'ddve-01.demo.local':  [5005] No space left on device",
        "result.error.reason": "The VM Direct engine 'localhost' is unable to back up the virtual machine 'Exchange' on vCenter 'VCenter' because the available space on the protection storage system 'ddve-01.demo.local' is insufficient.",
        "result.error.remediation": "Check the protection storage system to determine if there is enough free space for the operation. The PowerProtect DD Administration Guide provides more information on how to reclaim space.",
        "asset.name": "Exchange",
        "asset.type": null,
        "host.name": "esxi03-7.demo.local",
        "host.type": null,
        "inventorySource.type": null,
        "protectionPolicy.name": "Virtual Machines -Crash consistent -Test PLC",
        "protectionPolicy.type": null,
        "createTime": "2024-11-14T14:35:25.120Z",
        "endTime": "2024-11-14T14:35:32.070Z"
    },
    {
        "category": "PROTECT",
        "classType": "TASK",
        "result.status": "FAILED",
        "result.error.code": "ABV0026",
        "result.error.detailedDescription": "The VM Direct engine cannot complete the backup of this virtual machine because of a protection storage capacity issue on the PowerProtect DD.",
        "result.error.extendedReason": "Cannot create export directory 'Virtual_Machines_-Crash_consistent_--ppdm-01-ef2c3/PLCTLP-526629ba-5227-4c6f-a26d-0ff368976ef4/Stagings/4c6e8a0d-b323-44bf-b12b-da850be18bc5/52798cf3-8550-686b-9b30-3ad738e468a6/1731594928287951751' on 'ddve-01.demo.local':  [5005] No space left on device",
        "result.error.reason": "The VM Direct engine 'localhost' is unable to back up the virtual machine 'VMware vCenter Server' on vCenter 'VCenter' because the available space on the protection storage system 'ddve-01.demo.local' is insufficient.",
        "result.error.remediation": "Check the protection storage system to determine if there is enough free space for the operation. The PowerProtect DD Administration Guide provides more information on how to reclaim space.",
        "asset.name": "VMware vCenter Server",
        "asset.type": null,
        "host.name": "esxi03-7.demo.local",
        "host.type": null,
        "inventorySource.type": null,
        "protectionPolicy.name": "Virtual Machines -Crash consistent -Test PLC",
        "protectionPolicy.type": null,
        "createTime": "2024-11-14T14:35:25.195Z",
        "endTime": "2024-11-14T14:35:32.349Z"
    },
    {
        "category": "PROTECT",
        "classType": "TASK",
        "result.status": "FAILED",
        "result.error.code": "ABV0026",
        "result.error.detailedDescription": "The VM Direct engine cannot complete the backup of this virtual machine because of a protection storage capacity issue on the PowerProtect DD.",
        "result.error.extendedReason": "Cannot create export directory 'Virtual_Machines_-Crash_consistent_--ppdm-01-ef2c3/PLCTLP-526629ba-5227-4c6f-a26d-0ff368976ef4/Stagings/4c6e8a0d-b323-44bf-b12b-da850be18bc5/501f52ae-4cc5-59a3-42e9-018e757a20f3/1731594928204218893' on 'ddve-01.demo.local':  [5005] No space left on device",
        "result.error.reason": "The VM Direct engine 'localhost' is unable to back up the virtual machine 'sqlaag-02' on vCenter 'VCenter' because the available space on the protection storage system 'ddve-01.demo.local' is insufficient.",
        "result.error.remediation": "Check the protection storage system to determine if there is enough free space for the operation. The PowerProtect DD Administration Guide provides more information on how to reclaim space.",
        "asset.name": "sqlaag-02",
        "asset.type": null,
        "host.name": "esxi03-7.demo.local",
        "host.type": null,
        "inventorySource.type": null,
        "protectionPolicy.name": "Virtual Machines -Crash consistent -Test PLC",
        "protectionPolicy.type": null,
        "createTime": "2024-11-14T14:35:25.149Z",
        "endTime": "2024-11-14T14:35:32.255Z"
    },
    {
        "category": "PROTECT",
        "classType": "JOB",
        "result.status": "FAILED",
        "result.error.code": "AERR0019",
        "result.error.detailedDescription": "This task is unsuccessful because internal issue happens at service side.",
        "result.error.extendedReason": null,
        "result.error.reason": "This task is unsuccessful because internal issue happens at service side.",
        "result.error.remediation": "To troubleshoot this issue: wait for some time and then retry the operation again. If the issue persists, contact Dell Customer Support.",
        "asset.name": "VMware vCenter Server",
        "asset.type": "VMWARE_VIRTUAL_MACHINE",
        "host.name": null,
        "host.type": null,
        "inventorySource.type": "VCENTER",
        "protectionPolicy.name": "Virtual Machines -Crash consistent -Test PLC",
        "protectionPolicy.type": "VMWARE_VIRTUAL_MACHINE",
        "createTime": "2024-11-14T14:34:27.737Z",
        "endTime": "2024-11-14T14:35:33.287Z"
    },
    {
        "category": "PROTECT",
        "classType": "JOB",
        "result.status": "FAILED",
        "result.error.code": "AERR0019",
        "result.error.detailedDescription": "This task is unsuccessful because internal issue happens at service side.",
        "result.error.extendedReason": null,
        "result.error.reason": "This task is unsuccessful because internal issue happens at service side.",
        "result.error.remediation": "To troubleshoot this issue: wait for some time and then retry the operation again. If the issue persists, contact Dell Customer Support.",
        "asset.name": "Exchange",
        "asset.type": "VMWARE_VIRTUAL_MACHINE",
        "host.name": null,
        "host.type": null,
        "inventorySource.type": "VCENTER",
        "protectionPolicy.name": "Virtual Machines -Crash consistent -Test PLC",
        "protectionPolicy.type": "VMWARE_VIRTUAL_MACHINE",
        "createTime": "2024-11-14T14:34:26.099Z",
        "endTime": "2024-11-14T14:35:32.908Z"
    },
    {
        "category": "PROTECT",
        "classType": "JOB",
        "result.status": "FAILED",
        "result.error.code": "AERR0019",
        "result.error.detailedDescription": "This task is unsuccessful because internal issue happens at service side.",
        "result.error.extendedReason": null,
        "result.error.reason": "This task is unsuccessful because internal issue happens at service side.",
        "result.error.remediation": "To troubleshoot this issue: wait for some time and then retry the operation again. If the issue persists, contact Dell Customer Support.",
        "asset.name": "PPDM-01",
        "asset.type": "VMWARE_VIRTUAL_MACHINE",
        "host.name": null,
        "host.type": null,
        "inventorySource.type": "VCENTER",
        "protectionPolicy.name": "Virtual Machines -Crash consistent -Test PLC",
        "protectionPolicy.type": "VMWARE_VIRTUAL_MACHINE",
        "createTime": "2024-11-14T14:34:21.891Z",
        "endTime": "2024-11-14T14:35:32.589Z"
    },
    {
        "category": "PROTECT",
        "classType": "JOB",
        "result.status": "FAILED",
        "result.error.code": "AERR0019",
        "result.error.detailedDescription": "This task is unsuccessful because internal issue happens at service side.",
        "result.error.extendedReason": null,
        "result.error.reason": "This task is unsuccessful because internal issue happens at service side.",
        "result.error.remediation": "To troubleshoot this issue: wait for some time and then retry the operation again. If the issue persists, contact Dell Customer Support.",
        "asset.name": "sqlaag-02",
        "asset.type": "VMWARE_VIRTUAL_MACHINE",
        "host.name": null,
        "host.type": null,
        "inventorySource.type": "VCENTER",
        "protectionPolicy.name": "Virtual Machines -Crash consistent -Test PLC",
        "protectionPolicy.type": "VMWARE_VIRTUAL_MACHINE",
        "createTime": "2024-11-14T14:34:27.401Z",
        "endTime": "2024-11-14T14:35:33.300Z"
    },
    {
        "category": "PROTECT",
        "classType": "TASK",
        "result.status": "FAILED",
        "result.error.code": "ABA0002",
        "result.error.detailedDescription": "The protection policy backup was unsuccessful because of an agent issue.",
        "result.error.extendedReason": "Protection policy backup was unsuccessful because the Agent failed with the following error: Backup of database on host and instance is unsuccessful because of an internal server error. Check the ddbmsqlsv logs available in MSAPPAGENT logs directory on the host for more details.",
        "result.error.reason": "SQL Backups -TEST PLC: Unable to backup MICROSOFT_SQL_DATABASE asset DemoDB-01 on host sqlaag-02.demo.local to storage target SQL_Backups_-TEST_PLC-ppdm-01-f0af0 because of an agent issue.",
        "result.error.remediation": "Click export log and review the log file to determine the status of the job or check agent logs for more details.",
        "asset.name": "DemoDB-01",
        "asset.type": null,
        "host.name": "sqlaag-02.demo.local",
        "host.type": null,
        "inventorySource.type": null,
        "protectionPolicy.name": "SQL Backups -TEST PLC",
        "protectionPolicy.type": null,
        "createTime": "2024-11-14T14:34:18.800Z",
        "endTime": "2024-11-14T14:35:31.550Z"
    },
    {
        "category": "PROTECT",
        "classType": "TASK",
        "result.status": "FAILED",
        "result.error.code": "ABA0002",
        "result.error.detailedDescription": "The protection policy backup was unsuccessful because of an agent issue.",
        "result.error.extendedReason": "Protection policy backup was unsuccessful because the Agent failed with the following error: Backup of database on host and instance is unsuccessful because of an internal server error. Check the ddbmsqlsv logs available in MSAPPAGENT logs directory on the host for more details.",
        "result.error.reason": "SQL Backups -TEST PLC: Unable to backup MICROSOFT_SQL_DATABASE asset SQLDEV-02 on host SQL-02.demo.local to storage target SQL_Backups_-TEST_PLC-ppdm-01-f0af0 because of an agent issue.",
        "result.error.remediation": "Click export log and review the log file to determine the status of the job or check agent logs for more details.",
        "asset.name": "SQLDEV-02",
        "asset.type": null,
        "host.name": "SQL-02.demo.local",
        "host.type": null,
        "inventorySource.type": null,
        "protectionPolicy.name": "SQL Backups -TEST PLC",
        "protectionPolicy.type": null,
        "createTime": "2024-11-14T14:34:18.978Z",
        "endTime": "2024-11-14T14:35:34.155Z"
    },
    {
        "category": "PROTECT",
        "classType": "TASK",
        "result.status": "FAILED",
        "result.error.code": "ABA0002",
        "result.error.detailedDescription": "The protection policy backup was unsuccessful because of an agent issue.",
        "result.error.extendedReason": "Protection policy backup was unsuccessful because the Agent failed with the following error: Backup of database on host and instance is unsuccessful because of an internal server error. Check the ddbmsqlsv logs available in MSAPPAGENT logs directory on the host for more details.",
        "result.error.reason": "SQL Backups -TEST PLC: Unable to backup MICROSOFT_SQL_DATABASE asset msdb on host SQL-02.demo.local to storage target SQL_Backups_-TEST_PLC-ppdm-01-f0af0 because of an agent issue.",
        "result.error.remediation": "Click export log and review the log file to determine the status of the job or check agent logs for more details.",
        "asset.name": "msdb",
        "asset.type": null,
        "host.name": "SQL-02.demo.local",
        "host.type": null,
        "inventorySource.type": null,
        "protectionPolicy.name": "SQL Backups -TEST PLC",
        "protectionPolicy.type": null,
        "createTime": "2024-11-14T14:34:18.800Z",
        "endTime": "2024-11-14T14:35:34.152Z"
    },
    {
        "category": "PROTECT",
        "classType": "JOB",
        "result.status": "FAILED",
        "result.error.code": "ABA0002",
        "result.error.detailedDescription": "The protection policy backup was unsuccessful because of an agent issue.",
        "result.error.extendedReason": "Protection policy backup was unsuccessful because the Agent failed with the following error: Backup of database on host and instance is unsuccessful because of an internal server error. Check the ddbmsqlsv logs available in MSAPPAGENT logs directory on the host for more details.",
        "result.error.reason": "SQL Backups -TEST PLC: Unable to backup MICROSOFT_SQL_DATABASE asset model on host SQL-02.demo.local to storage target SQL_Backups_-TEST_PLC-ppdm-01-f0af0 because of an agent issue.",
        "result.error.remediation": "Click export log and review the log file to determine the status of the job or check agent logs for more details.",
        "asset.name": "model",
        "asset.type": "MICROSOFT_SQL_DATABASE",
        "host.name": "SQL-02.demo.local",
        "host.type": "APP_HOST",
        "inventorySource.type": null,
        "protectionPolicy.name": "SQL Backups -TEST PLC",
        "protectionPolicy.type": "MICROSOFT_SQL_DATABASE",
        "createTime": "2024-11-14T14:34:16.456Z",
        "endTime": "2024-11-14T14:35:34.868Z"
    },
    {
        "category": "PROTECT",
        "classType": "TASK",
        "result.status": "FAILED",
        "result.error.code": "ABA0002",
        "result.error.detailedDescription": "The protection policy backup was unsuccessful because of an agent issue.",
        "result.error.extendedReason": "Protection policy backup was unsuccessful because the Agent failed with the following error: Backup of database on host and instance is unsuccessful because of an internal server error. Check the ddbmsqlsv logs available in MSAPPAGENT logs directory on the host for more details.",
        "result.error.reason": "SQL Backups -TEST PLC: Unable to backup MICROSOFT_SQL_DATABASE asset SQLPROD-02 on host SQL-02.demo.local to storage target SQL_Backups_-TEST_PLC-ppdm-01-f0af0 because of an agent issue.",
        "result.error.remediation": "Click export log and review the log file to determine the status of the job or check agent logs for more details.",
        "asset.name": "SQLPROD-02",
        "asset.type": null,
        "host.name": "SQL-02.demo.local",
        "host.type": null,
        "inventorySource.type": null,
        "protectionPolicy.name": "SQL Backups -TEST PLC",
        "protectionPolicy.type": null,
        "createTime": "2024-11-14T14:34:18.802Z",
        "endTime": "2024-11-14T14:35:34.184Z"
    },
    {
        "category": "PROTECT",
        "classType": "JOB",
        "result.status": "FAILED",
        "result.error.code": "ABA0002",
        "result.error.detailedDescription": "The protection policy backup was unsuccessful because of an agent issue.",
        "result.error.extendedReason": "Protection policy backup was unsuccessful because the Agent failed with the following error: Backup of database on host and instance is unsuccessful because of an internal server error. Check the ddbmsqlsv logs available in MSAPPAGENT logs directory on the host for more details.",
        "result.error.reason": "SQL Backups -TEST PLC: Unable to backup MICROSOFT_SQL_DATABASE asset msdb on host SQL-02.demo.local to storage target SQL_Backups_-TEST_PLC-ppdm-01-f0af0 because of an agent issue.",
        "result.error.remediation": "Click export log and review the log file to determine the status of the job or check agent logs for more details.",
        "asset.name": "msdb",
        "asset.type": "MICROSOFT_SQL_DATABASE",
        "host.name": "SQL-02.demo.local",
        "host.type": "APP_HOST",
        "inventorySource.type": null,
        "protectionPolicy.name": "SQL Backups -TEST PLC",
        "protectionPolicy.type": "MICROSOFT_SQL_DATABASE",
        "createTime": "2024-11-14T14:34:13.897Z",
        "endTime": "2024-11-14T14:35:34.716Z"
    },
    {
        "category": "PROTECT",
        "classType": "JOB",
        "result.status": "FAILED",
        "result.error.code": "ABA0002",
        "result.error.detailedDescription": "The protection policy backup was unsuccessful because of an agent issue.",
        "result.error.extendedReason": "Protection policy backup was unsuccessful because the Agent failed with the following error: Backup of database on host and instance is unsuccessful because of an internal server error. Check the ddbmsqlsv logs available in MSAPPAGENT logs directory on the host for more details.",
        "result.error.reason": "SQL Backups -TEST PLC: Unable to backup MICROSOFT_SQL_DATABASE asset SQLPROD-02 on host SQL-02.demo.local to storage target SQL_Backups_-TEST_PLC-ppdm-01-f0af0 because of an agent issue.",
        "result.error.remediation": "Click export log and review the log file to determine the status of the job or check agent logs for more details.",
        "asset.name": "SQLPROD-02",
        "asset.type": "MICROSOFT_SQL_DATABASE",
        "host.name": "SQL-02.demo.local",
        "host.type": "APP_HOST",
        "inventorySource.type": null,
        "protectionPolicy.name": "SQL Backups -TEST PLC",
        "protectionPolicy.type": "MICROSOFT_SQL_DATABASE",
        "createTime": "2024-11-14T14:34:16.103Z",
        "endTime": "2024-11-14T14:35:35.943Z"
    },
    {
        "category": "PROTECT",
        "classType": "TASK",
        "result.status": "FAILED",
        "result.error.code": "ABA0002",
        "result.error.detailedDescription": "The protection policy backup was unsuccessful because of an agent issue.",
        "result.error.extendedReason": "Protection policy backup was unsuccessful because the Agent failed with the following error: Backup of database on host and instance is unsuccessful because of an internal server error. Check the ddbmsqlsv logs available in MSAPPAGENT logs directory on the host for more details.",
        "result.error.reason": "SQL Backups -TEST PLC: Unable to backup MICROSOFT_SQL_DATABASE asset master on host SQL-02.demo.local to storage target SQL_Backups_-TEST_PLC-ppdm-01-f0af0 because of an agent issue.",
        "result.error.remediation": "Click export log and review the log file to determine the status of the job or check agent logs for more details.",
        "asset.name": "master",
        "asset.type": null,
        "host.name": "SQL-02.demo.local",
        "host.type": null,
        "inventorySource.type": null,
        "protectionPolicy.name": "SQL Backups -TEST PLC",
        "protectionPolicy.type": null,
        "createTime": "2024-11-14T14:34:18.799Z",
        "endTime": "2024-11-14T14:35:34.146Z"
    },
    {
        "category": "PROTECT",
        "classType": "TASK",
        "result.status": "FAILED",
        "result.error.code": "ABA0002",
        "result.error.detailedDescription": "The protection policy backup was unsuccessful because of an agent issue.",
        "result.error.extendedReason": "Protection policy backup was unsuccessful because the Agent failed with the following error: Backup of database on host and instance is unsuccessful because of an internal server error. Check the ddbmsqlsv logs available in MSAPPAGENT logs directory on the host for more details.",
        "result.error.reason": "SQL Backups -TEST PLC: Unable to backup MICROSOFT_SQL_DATABASE asset model on host SQL-02.demo.local to storage target SQL_Backups_-TEST_PLC-ppdm-01-f0af0 because of an agent issue.",
        "result.error.remediation": "Click export log and review the log file to determine the status of the job or check agent logs for more details.",
        "asset.name": "model",
        "asset.type": null,
        "host.name": "SQL-02.demo.local",
        "host.type": null,
        "inventorySource.type": null,
        "protectionPolicy.name": "SQL Backups -TEST PLC",
        "protectionPolicy.type": null,
        "createTime": "2024-11-14T14:34:18.934Z",
        "endTime": "2024-11-14T14:35:34.164Z"
    },
    {
        "category": "PROTECT",
        "classType": "JOB",
        "result.status": "FAILED",
        "result.error.code": "ABA0002",
        "result.error.detailedDescription": "The protection policy backup was unsuccessful because of an agent issue.",
        "result.error.extendedReason": "Protection policy backup was unsuccessful because the Agent failed with the following error: Backup of database on host and instance is unsuccessful because of an internal server error. Check the ddbmsqlsv logs available in MSAPPAGENT logs directory on the host for more details.",
        "result.error.reason": "SQL Backups -TEST PLC: Unable to backup MICROSOFT_SQL_DATABASE asset SQLQA-02 on host SQL-02.demo.local to storage target SQL_Backups_-TEST_PLC-ppdm-01-f0af0 because of an agent issue.",
        "result.error.remediation": "Click export log and review the log file to determine the status of the job or check agent logs for more details.",
        "asset.name": "SQLQA-02",
        "asset.type": "MICROSOFT_SQL_DATABASE",
        "host.name": "SQL-02.demo.local",
        "host.type": "APP_HOST",
        "inventorySource.type": null,
        "protectionPolicy.name": "SQL Backups -TEST PLC",
        "protectionPolicy.type": "MICROSOFT_SQL_DATABASE",
        "createTime": "2024-11-14T14:34:15.949Z",
        "endTime": "2024-11-14T14:35:35.749Z"
    },
    {
        "category": "PROTECT",
        "classType": "TASK",
        "result.status": "FAILED",
        "result.error.code": "ABNA0020",
        "result.error.detailedDescription": "The existence of the target asset cannot be validated.",
        "result.error.extendedReason": "NAS vProxy Engine nas-proxy.demo.local is unable to perform SnapshotAndSlice operation for nasShare /ifs/data/csi/k8s-33b51b73dd. \n\nError Details:\n TaskId: 8857c8d8-e01c-4ea5-be83-c232fc31f8bd, JobId 8857c8d8-e01c-4ea5-be83-c232fc31f8bd \n NAS agent error code 'ABNA0020'. Unable to complete the 'SNAPSHOT_AND_SLICE' operation because the location for asset '/ifs/data/csi/k8s-33b51b73dd' could not be validated in PowerScale/Isilon NAS '192.168.1.108'.. \n",
        "result.error.reason": "Unable to complete a SNAPSHOT_AND_SLICE operation because the location for asset /ifs/data/csi/k8s-33b51b73dd could not be validated in PowerScale/Isilon NAS 192.168.1.108.",
        "result.error.remediation": "Connect to the PowerScale/Isilon NAS and verify that the share exists. \nFrom the PowerProtect Data Manager Asset Source page, perform an on-demand discovery of assets from this asset source.",
        "asset.name": null,
        "asset.type": "NAS_SHARE",
        "host.name": null,
        "host.type": null,
        "inventorySource.type": null,
        "protectionPolicy.name": "NAS Backups - TEST PLC",
        "protectionPolicy.type": "NAS_SHARE",
        "createTime": "2024-11-14T14:34:07.753Z",
        "endTime": "2024-11-14T14:35:41.220Z"
    },
    {
        "category": "PROTECT",
        "classType": "TASK",
        "result.status": "SKIPPED",
        "result.error.code": "AERR0004",
        "result.error.detailedDescription": "This task cannot be completed when dependent protection tasks do not complete successfully.",
        "result.error.extendedReason": null,
        "result.error.reason": "Task Performing data rollover for the slices created was skipped because the protection task was unsuccessful.",
        "result.error.remediation": "Review the details for the protection task in the Jobs window to troubleshoot the issue. When the issue is resolved, retry the protection job task. If the issue persists, contact Dell Customer Support.",
        "asset.name": null,
        "asset.type": "NAS_SHARE",
        "host.name": null,
        "host.type": null,
        "inventorySource.type": null,
        "protectionPolicy.name": "NAS Backups - TEST PLC",
        "protectionPolicy.type": "NAS_SHARE",
        "createTime": "2024-11-14T14:34:07.817Z",
        "endTime": "2024-11-14T14:35:41.355Z"
    },
    {
        "category": "PROTECT",
        "classType": "TASK",
        "result.status": "FAILED",
        "result.error.code": "ABNA0020",
        "result.error.detailedDescription": "The existence of the target asset cannot be validated.",
        "result.error.extendedReason": "NAS vProxy Engine nas-proxy.demo.local is unable to perform SnapshotAndSlice operation for nasShare /ifs/data/csi/k8s-0aa9eb47f2. \n\nError Details:\n TaskId: 96005fb6-2159-43a4-9233-1ca5bc46e5a0, JobId 96005fb6-2159-43a4-9233-1ca5bc46e5a0 \n NAS agent error code 'ABNA0020'. Unable to complete the 'SNAPSHOT_AND_SLICE' operation because the location for asset '/ifs/data/csi/k8s-0aa9eb47f2' could not be validated in PowerScale/Isilon NAS '192.168.1.108'.. \n",
        "result.error.reason": "Unable to complete a SNAPSHOT_AND_SLICE operation because the location for asset /ifs/data/csi/k8s-0aa9eb47f2 could not be validated in PowerScale/Isilon NAS 192.168.1.108.",
        "result.error.remediation": "Connect to the PowerScale/Isilon NAS and verify that the share exists. \nFrom the PowerProtect Data Manager Asset Source page, perform an on-demand discovery of assets from this asset source.",
        "asset.name": null,
        "asset.type": "NAS_SHARE",
        "host.name": null,
        "host.type": null,
        "inventorySource.type": null,
        "protectionPolicy.name": "NAS Backups - TEST PLC",
        "protectionPolicy.type": "NAS_SHARE",
        "createTime": "2024-11-14T14:34:08.090Z",
        "endTime": "2024-11-14T14:35:45.238Z"
    },
    {
        "category": "PROTECT",
        "classType": "TASK",
        "result.status": "SKIPPED",
        "result.error.code": "AERR0004",
        "result.error.detailedDescription": "This task cannot be completed when dependent protection tasks do not complete successfully.",
        "result.error.extendedReason": null,
        "result.error.reason": "Task Performing data rollover for the slices created was skipped because the protection task was unsuccessful.",
        "result.error.remediation": "Review the details for the protection task in the Jobs window to troubleshoot the issue. When the issue is resolved, retry the protection job task. If the issue persists, contact Dell Customer Support.",
        "asset.name": null,
        "asset.type": "NAS_SHARE",
        "host.name": null,
        "host.type": null,
        "inventorySource.type": null,
        "protectionPolicy.name": "NAS Backups - TEST PLC",
        "protectionPolicy.type": "NAS_SHARE",
        "createTime": "2024-11-14T14:34:08.120Z",
        "endTime": "2024-11-14T14:35:45.381Z"
    },
    {
        "category": "PROTECT",
        "classType": "JOB",
        "result.status": "FAILED",
        "result.error.code": "ABNA0020",
        "result.error.detailedDescription": "The existence of the target asset cannot be validated.",
        "result.error.extendedReason": "NAS vProxy Engine nas-proxy.demo.local is unable to perform SnapshotAndSlice operation for nasShare /ifs/data/csi/k8s-33b51b73dd. \n\nError Details:\n TaskId: 8857c8d8-e01c-4ea5-be83-c232fc31f8bd, JobId 8857c8d8-e01c-4ea5-be83-c232fc31f8bd \n NAS agent error code 'ABNA0020'. Unable to complete the 'SNAPSHOT_AND_SLICE' operation because the location for asset '/ifs/data/csi/k8s-33b51b73dd' could not be validated in PowerScale/Isilon NAS '192.168.1.108'.. \n",
        "result.error.reason": "Unable to complete a SNAPSHOT_AND_SLICE operation because the location for asset /ifs/data/csi/k8s-33b51b73dd could not be validated in PowerScale/Isilon NAS 192.168.1.108.",
        "result.error.remediation": "Connect to the PowerScale/Isilon NAS and verify that the share exists. \nFrom the PowerProtect Data Manager Asset Source page, perform an on-demand discovery of assets from this asset source.",
        "asset.name": "/ifs/data/csi/k8s-33b51b73dd",
        "asset.type": "NAS_SHARE",
        "host.name": null,
        "host.type": null,
        "inventorySource.type": null,
        "protectionPolicy.name": "NAS Backups - TEST PLC",
        "protectionPolicy.type": "NAS_SHARE",
        "createTime": "2024-11-14T14:34:07.661Z",
        "endTime": "2024-11-14T14:36:05.066Z"
    },
    {
        "category": "PROTECT",
        "classType": "JOB",
        "result.status": "FAILED",
        "result.error.code": "ABNA0020",
        "result.error.detailedDescription": "The existence of the target asset cannot be validated.",
        "result.error.extendedReason": "NAS vProxy Engine nas-proxy.demo.local is unable to perform SnapshotAndSlice operation for nasShare /ifs/data/csi/k8s-0aa9eb47f2. \n\nError Details:\n TaskId: 96005fb6-2159-43a4-9233-1ca5bc46e5a0, JobId 96005fb6-2159-43a4-9233-1ca5bc46e5a0 \n NAS agent error code 'ABNA0020'. Unable to complete the 'SNAPSHOT_AND_SLICE' operation because the location for asset '/ifs/data/csi/k8s-0aa9eb47f2' could not be validated in PowerScale/Isilon NAS '192.168.1.108'.. \n",
        "result.error.reason": "Unable to complete a SNAPSHOT_AND_SLICE operation because the location for asset /ifs/data/csi/k8s-0aa9eb47f2 could not be validated in PowerScale/Isilon NAS 192.168.1.108.",
        "result.error.remediation": "Connect to the PowerScale/Isilon NAS and verify that the share exists. \nFrom the PowerProtect Data Manager Asset Source page, perform an on-demand discovery of assets from this asset source.",
        "asset.name": "/ifs/data/csi/k8s-0aa9eb47f2",
        "asset.type": "NAS_SHARE",
        "host.name": null,
        "host.type": null,
        "inventorySource.type": null,
        "protectionPolicy.name": "NAS Backups - TEST PLC",
        "protectionPolicy.type": "NAS_SHARE",
        "createTime": "2024-11-14T14:34:08.056Z",
        "endTime": "2024-11-14T14:36:05.075Z"
    },
    {
        "category": "PROTECT",
        "classType": "JOB",
        "result.status": "FAILED",
        "result.error.code": "ABNA0020",
        "result.error.detailedDescription": "The existence of the target asset cannot be validated.",
        "result.error.extendedReason": "NAS vProxy Engine nas-proxy.demo.local is unable to perform SnapshotAndSlice operation for nasShare /ifs/data/csi/k8s-418144021c. \n\nError Details:\n TaskId: 1e3c2f2e-dba1-44b3-a958-c6ae530a33d0, JobId 1e3c2f2e-dba1-44b3-a958-c6ae530a33d0 \n NAS agent error code 'ABNA0020'. Unable to complete the 'SNAPSHOT_AND_SLICE' operation because the location for asset '/ifs/data/csi/k8s-418144021c' could not be validated in PowerScale/Isilon NAS '192.168.1.108'.. \n",
        "result.error.reason": "Unable to complete a SNAPSHOT_AND_SLICE operation because the location for asset /ifs/data/csi/k8s-418144021c could not be validated in PowerScale/Isilon NAS 192.168.1.108.",
        "result.error.remediation": "Connect to the PowerScale/Isilon NAS and verify that the share exists. \nFrom the PowerProtect Data Manager Asset Source page, perform an on-demand discovery of assets from this asset source.",
        "asset.name": "/ifs/data/csi/k8s-418144021c",
        "asset.type": "NAS_SHARE",
        "host.name": null,
        "host.type": null,
        "inventorySource.type": null,
        "protectionPolicy.name": "NAS Backups - TEST PLC",
        "protectionPolicy.type": "NAS_SHARE",
        "createTime": "2024-11-14T14:34:08.259Z",
        "endTime": "2024-11-14T14:36:04.850Z"
    },
    {
        "category": "PROTECT",
        "classType": "TASK",
        "result.status": "FAILED",
        "result.error.code": "ABV0026",
        "result.error.detailedDescription": "The VM Direct engine cannot complete the backup of this virtual machine because of a protection storage capacity issue on the PowerProtect DD.",
        "result.error.extendedReason": "Cannot create export directory 'Virtual_Machines_-Crash_consistent_--ppdm-01-ef2c3/PLCTLP-526629ba-5227-4c6f-a26d-0ff368976ef4/Stagings/4c6e8a0d-b323-44bf-b12b-da850be18bc5/501f25a4-72e6-34bf-fd80-0efdac900bd2/1731594990391754007' on 'ddve-01.demo.local':  [5005] No space left on device",
        "result.error.reason": "The VM Direct engine 'localhost' is unable to back up the virtual machine 'k8-master01' on vCenter 'VCenter' because the available space on the protection storage system 'ddve-01.demo.local' is insufficient.",
        "result.error.remediation": "Check the protection storage system to determine if there is enough free space for the operation. The PowerProtect DD Administration Guide provides more information on how to reclaim space.",
        "asset.name": "k8-master01",
        "asset.type": null,
        "host.name": "esxi01-7.demo.local",
        "host.type": null,
        "inventorySource.type": null,
        "protectionPolicy.name": "Virtual Machines -Crash consistent -Test PLC",
        "protectionPolicy.type": null,
        "createTime": "2024-11-14T14:36:28.132Z",
        "endTime": "2024-11-14T14:36:34.309Z"
    },
    {
        "category": "PROTECT",
        "classType": "JOB",
        "result.status": "FAILED",
        "result.error.code": "AERR0019",
        "result.error.detailedDescription": "This task is unsuccessful because internal issue happens at service side.",
        "result.error.extendedReason": null,
        "result.error.reason": "This task is unsuccessful because internal issue happens at service side.",
        "result.error.remediation": "To troubleshoot this issue: wait for some time and then retry the operation again. If the issue persists, contact Dell Customer Support.",
        "asset.name": "k8-master01",
        "asset.type": "VMWARE_VIRTUAL_MACHINE",
        "host.name": null,
        "host.type": null,
        "inventorySource.type": "VCENTER",
        "protectionPolicy.name": "Virtual Machines -Crash consistent -Test PLC",
        "protectionPolicy.type": "VMWARE_VIRTUAL_MACHINE",
        "createTime": "2024-11-14T14:34:23.833Z",
        "endTime": "2024-11-14T14:36:34.577Z"
    },
    {
        "category": "PROTECT",
        "classType": "TASK",
        "result.status": "FAILED",
        "result.error.code": "ABV0026",
        "result.error.detailedDescription": "The VM Direct engine cannot complete the backup of this virtual machine because of a protection storage capacity issue on the PowerProtect DD.",
        "result.error.extendedReason": "Cannot create export directory 'Virtual_Machines_-Crash_consistent_--ppdm-01-ef2c3/PLCTLP-526629ba-5227-4c6f-a26d-0ff368976ef4/Stagings/4c6e8a0d-b323-44bf-b12b-da850be18bc5/501ff233-101a-7719-e1a6-5f0964cdd7e8/1731595021451220419' on 'ddve-01.demo.local':  [5005] No space left on device",
        "result.error.reason": "The VM Direct engine 'localhost' is unable to back up the virtual machine 'k8-node01' on vCenter 'VCenter' because the available space on the protection storage system 'ddve-01.demo.local' is insufficient.",
        "result.error.remediation": "Check the protection storage system to determine if there is enough free space for the operation. The PowerProtect DD Administration Guide provides more information on how to reclaim space.",
        "asset.name": "k8-node01",
        "asset.type": null,
        "host.name": "esxi01-7.demo.local",
        "host.type": null,
        "inventorySource.type": null,
        "protectionPolicy.name": "Virtual Machines -Crash consistent -Test PLC",
        "protectionPolicy.type": null,
        "createTime": "2024-11-14T14:36:58.938Z",
        "endTime": "2024-11-14T14:37:05.410Z"
    },
    {
        "category": "PROTECT",
        "classType": "JOB",
        "result.status": "FAILED",
        "result.error.code": "AERR0019",
        "result.error.detailedDescription": "This task is unsuccessful because internal issue happens at service side.",
        "result.error.extendedReason": null,
        "result.error.reason": "This task is unsuccessful because internal issue happens at service side.",
        "result.error.remediation": "To troubleshoot this issue: wait for some time and then retry the operation again. If the issue persists, contact Dell Customer Support.",
        "asset.name": "k8-node01",
        "asset.type": "VMWARE_VIRTUAL_MACHINE",
        "host.name": null,
        "host.type": null,
        "inventorySource.type": "VCENTER",
        "protectionPolicy.name": "Virtual Machines -Crash consistent -Test PLC",
        "protectionPolicy.type": "VMWARE_VIRTUAL_MACHINE",
        "createTime": "2024-11-14T14:34:24.888Z",
        "endTime": "2024-11-14T14:37:05.702Z"
    },
    {
        "category": "CONFIG",
        "classType": "TASK",
        "result.status": "FAILED",
        "result.error.code": "ABV0025",
        "result.error.detailedDescription": "The VM Direct engine cannot complete protection of this virtual machine because the protection configuration was unsuccessful.",
        "result.error.extendedReason": "Unable to configure protection for the asset because SCSI sharing and is not supported.",
        "result.error.reason": "VM Direct engine is unable to configure protection for the virtual machine 'win-10' on vCenter 'VCenter'.",
        "result.error.remediation": "Review the error details and summary log in the Jobs window, or export the job logs and review the log files for more information. If the issue persists, contact Dell Customer Support.",
        "asset.name": "win-10",
        "asset.type": null,
        "host.name": null,
        "host.type": null,
        "inventorySource.type": null,
        "protectionPolicy.name": "Virtual Machines -Crash consistent -Test PLC",
        "protectionPolicy.type": null,
        "createTime": "2024-11-14T14:37:30.391Z",
        "endTime": "2024-11-14T14:37:31.230Z"
    },
    {
        "category": "PROTECT",
        "classType": "JOB",
        "result.status": "FAILED",
        "result.error.code": "ABV0025",
        "result.error.detailedDescription": "The VM Direct engine cannot complete protection of this virtual machine because the protection configuration was unsuccessful.",
        "result.error.extendedReason": "Unable to configure protection for the asset because SCSI sharing and is not supported.",
        "result.error.reason": "VM Direct engine is unable to configure protection for the virtual machine 'win-10' on vCenter 'VCenter'.",
        "result.error.remediation": "Review the error details and summary log in the Jobs window, or export the job logs and review the log files for more information. If the issue persists, contact Dell Customer Support.",
        "asset.name": "win-10",
        "asset.type": "VMWARE_VIRTUAL_MACHINE",
        "host.name": null,
        "host.type": null,
        "inventorySource.type": "VCENTER",
        "protectionPolicy.name": "Virtual Machines -Crash consistent -Test PLC",
        "protectionPolicy.type": "VMWARE_VIRTUAL_MACHINE",
        "createTime": "2024-11-14T14:34:26.476Z",
        "endTime": "2024-11-14T14:37:32.164Z"
    },
    {
        "category": "PROTECT",
        "classType": "TASK",
        "result.status": "FAILED",
        "result.error.code": "ABNA0013",
        "result.error.detailedDescription": "A stub file cannot be created on the PowerProtect DD System to get a unique transaction ID backup.",
        "result.error.extendedReason": "NAS vProxy Engine nas-proxy.demo.local is unable to perform SnapshotAndSlice operation for nasShare win-share01. \n\nError Details:\n TaskId: 3b374ef6-4083-4e89-a858-c49a8cc4116c, JobId 3b374ef6-4083-4e89-a858-c49a8cc4116c \n NAS agent error code 'ABNA0013'. Unable to create a save set with a timestamp: 1731595021569093435.\n. \n",
        "result.error.reason": "Unable to complete the SNAPSHOT_AND_SLICE operation because a backup copy ID for share win-share01 could not be generated.",
        "result.error.remediation": "To troubleshoot this issue: \n1) Check for connectivity between the PowerProtect DD system, PowerProtect Data Manager, and the NAS protection engine. \n2) Verify that there is enough storage space on the PowerProtect DD system and that the corresponding Storage Unit (SU) is accessible. \n3) Retry the operation. If the issue persists, contact Dell Customer Support.",
        "asset.name": null,
        "asset.type": "NAS_SHARE",
        "host.name": null,
        "host.type": null,
        "inventorySource.type": null,
        "protectionPolicy.name": "NAS Backups - TEST PLC",
        "protectionPolicy.type": "NAS_SHARE",
        "createTime": "2024-11-14T14:34:08.882Z",
        "endTime": "2024-11-14T14:37:38.881Z"
    },
    {
        "category": "PROTECT",
        "classType": "TASK",
        "result.status": "SKIPPED",
        "result.error.code": "AERR0004",
        "result.error.detailedDescription": "This task cannot be completed when dependent protection tasks do not complete successfully.",
        "result.error.extendedReason": null,
        "result.error.reason": "Task Performing data rollover for the slices created was skipped because the protection task was unsuccessful.",
        "result.error.remediation": "Review the details for the protection task in the Jobs window to troubleshoot the issue. When the issue is resolved, retry the protection job task. If the issue persists, contact Dell Customer Support.",
        "asset.name": null,
        "asset.type": "NAS_SHARE",
        "host.name": null,
        "host.type": null,
        "inventorySource.type": null,
        "protectionPolicy.name": "NAS Backups - TEST PLC",
        "protectionPolicy.type": "NAS_SHARE",
        "createTime": "2024-11-14T14:34:08.911Z",
        "endTime": "2024-11-14T14:37:39.055Z"
    },
    {
        "category": "PROTECT",
        "classType": "TASK",
        "result.status": "FAILED",
        "result.error.code": "ABNA0013",
        "result.error.detailedDescription": "A stub file cannot be created on the PowerProtect DD System to get a unique transaction ID backup.",
        "result.error.extendedReason": "NAS vProxy Engine nas-proxy.demo.local is unable to perform SnapshotAndSlice operation for nasShare win-share02. \n\nError Details:\n TaskId: b5d4d388-8da1-4c01-9f4b-0349864d92d3, JobId b5d4d388-8da1-4c01-9f4b-0349864d92d3 \n NAS agent error code 'ABNA0013'. Unable to create a save set with a timestamp: 1731595086493925189.\n. \n",
        "result.error.reason": "Unable to complete the SNAPSHOT_AND_SLICE operation because a backup copy ID for share win-share02 could not be generated.",
        "result.error.remediation": "To troubleshoot this issue: \n1) Check for connectivity between the PowerProtect DD system, PowerProtect Data Manager, and the NAS protection engine. \n2) Verify that there is enough storage space on the PowerProtect DD system and that the corresponding Storage Unit (SU) is accessible. \n3) Retry the operation. If the issue persists, contact Dell Customer Support.",
        "asset.name": null,
        "asset.type": "NAS_SHARE",
        "host.name": null,
        "host.type": null,
        "inventorySource.type": null,
        "protectionPolicy.name": "NAS Backups - TEST PLC",
        "protectionPolicy.type": "NAS_SHARE",
        "createTime": "2024-11-14T14:34:09.098Z",
        "endTime": "2024-11-14T14:38:12.696Z"
    },
    {
        "category": "PROTECT",
        "classType": "TASK",
        "result.status": "SKIPPED",
        "result.error.code": "AERR0004",
        "result.error.detailedDescription": "This task cannot be completed when dependent protection tasks do not complete successfully.",
        "result.error.extendedReason": null,
        "result.error.reason": "Task Performing data rollover for the slices created was skipped because the protection task was unsuccessful.",
        "result.error.remediation": "Review the details for the protection task in the Jobs window to troubleshoot the issue. When the issue is resolved, retry the protection job task. If the issue persists, contact Dell Customer Support.",
        "asset.name": null,
        "asset.type": "NAS_SHARE",
        "host.name": null,
        "host.type": null,
        "inventorySource.type": null,
        "protectionPolicy.name": "NAS Backups - TEST PLC",
        "protectionPolicy.type": "NAS_SHARE",
        "createTime": "2024-11-14T14:34:09.127Z",
        "endTime": "2024-11-14T14:38:12.822Z"
    },
    {
        "category": "PROTECT",
        "classType": "JOB",
        "result.status": "FAILED",
        "result.error.code": "ABNA0013",
        "result.error.detailedDescription": "A stub file cannot be created on the PowerProtect DD System to get a unique transaction ID backup.",
        "result.error.extendedReason": "NAS vProxy Engine nas-proxy.demo.local is unable to perform SnapshotAndSlice operation for nasShare win-share02. \n\nError Details:\n TaskId: b5d4d388-8da1-4c01-9f4b-0349864d92d3, JobId b5d4d388-8da1-4c01-9f4b-0349864d92d3 \n NAS agent error code 'ABNA0013'. Unable to create a save set with a timestamp: 1731595086493925189.\n. \n",
        "result.error.reason": "Unable to complete the SNAPSHOT_AND_SLICE operation because a backup copy ID for share win-share02 could not be generated.",
        "result.error.remediation": "To troubleshoot this issue: \n1) Check for connectivity between the PowerProtect DD system, PowerProtect Data Manager, and the NAS protection engine. \n2) Verify that there is enough storage space on the PowerProtect DD system and that the corresponding Storage Unit (SU) is accessible. \n3) Retry the operation. If the issue persists, contact Dell Customer Support.",
        "asset.name": "win-share02",
        "asset.type": "NAS_SHARE",
        "host.name": null,
        "host.type": null,
        "inventorySource.type": null,
        "protectionPolicy.name": "NAS Backups - TEST PLC",
        "protectionPolicy.type": "NAS_SHARE",
        "createTime": "2024-11-14T14:34:09.068Z",
        "endTime": "2024-11-14T14:38:37.811Z"
    },
    {
        "category": "PROTECT",
        "classType": "JOB",
        "result.status": "FAILED",
        "result.error.code": "ABA0002",
        "result.error.detailedDescription": "The protection policy backup was unsuccessful because of an agent issue.",
        "result.error.extendedReason": "Protection policy backup was unsuccessful because the Agent failed with the following error: SQLite database initialization failed.",
        "result.error.reason": "Filesystem Backups -TEST PLC: Unable to backup FILE_SYSTEM asset F:\\ on host win-11.demo.local to storage target Filesystem_Backups_-TEST_PLC-ppdm-01-b89b3 because of an agent issue.",
        "result.error.remediation": "Click export log and review the log file to determine the status of the job or check agent logs for more details.",
        "asset.name": "F:\\",
        "asset.type": "FILE_SYSTEM",
        "host.name": "win-11.demo.local",
        "host.type": "APP_HOST",
        "inventorySource.type": null,
        "protectionPolicy.name": "Filesystem Backups -TEST PLC",
        "protectionPolicy.type": "FILE_SYSTEM",
        "createTime": "2024-11-14T14:33:57.418Z",
        "endTime": "2024-11-14T14:45:31.615Z"
    },
    {
        "category": "PROTECT",
        "classType": "TASK",
        "result.status": "FAILED",
        "result.error.code": "ABA0002",
        "result.error.detailedDescription": "The protection policy backup was unsuccessful because of an agent issue.",
        "result.error.extendedReason": "Protection policy backup was unsuccessful because the Agent failed with the following error: SQLite database initialization failed.",
        "result.error.reason": "Filesystem Backups -TEST PLC: Unable to backup FILE_SYSTEM asset C:\\ on host win-11.demo.local to storage target Filesystem_Backups_-TEST_PLC-ppdm-01-b89b3 because of an agent issue.",
        "result.error.remediation": "Click export log and review the log file to determine the status of the job or check agent logs for more details.",
        "asset.name": "C:\\",
        "asset.type": null,
        "host.name": "win-11.demo.local",
        "host.type": null,
        "inventorySource.type": null,
        "protectionPolicy.name": "Filesystem Backups -TEST PLC",
        "protectionPolicy.type": null,
        "createTime": "2024-11-14T14:34:18.922Z",
        "endTime": "2024-11-14T14:45:31.267Z"
    },
    {
        "category": "PROTECT",
        "classType": "TASK",
        "result.status": "FAILED",
        "result.error.code": "ABA0002",
        "result.error.detailedDescription": "The protection policy backup was unsuccessful because of an agent issue.",
        "result.error.extendedReason": "Protection policy backup was unsuccessful because the Agent failed with the following error: SQLite database initialization failed.",
        "result.error.reason": "Filesystem Backups -TEST PLC: Unable to backup FILE_SYSTEM asset E:\\ on host win-10.demo.local to storage target Filesystem_Backups_-TEST_PLC-ppdm-01-b89b3 because of an agent issue.",
        "result.error.remediation": "Click export log and review the log file to determine the status of the job or check agent logs for more details.",
        "asset.name": "E:\\",
        "asset.type": null,
        "host.name": "win-10.demo.local",
        "host.type": null,
        "inventorySource.type": null,
        "protectionPolicy.name": "Filesystem Backups -TEST PLC",
        "protectionPolicy.type": null,
        "createTime": "2024-11-14T14:34:18.798Z",
        "endTime": "2024-11-14T14:45:30.942Z"
    },
    {
        "category": "PROTECT",
        "classType": "TASK",
        "result.status": "FAILED",
        "result.error.code": "ABA0002",
        "result.error.detailedDescription": "The protection policy backup was unsuccessful because of an agent issue.",
        "result.error.extendedReason": "Protection policy backup was unsuccessful because the Agent failed with the following error: SQLite database initialization failed.",
        "result.error.reason": "Filesystem Backups -TEST PLC: Unable to backup FILE_SYSTEM asset F:\\ on host win-11.demo.local to storage target Filesystem_Backups_-TEST_PLC-ppdm-01-b89b3 because of an agent issue.",
        "result.error.remediation": "Click export log and review the log file to determine the status of the job or check agent logs for more details.",
        "asset.name": "F:\\",
        "asset.type": null,
        "host.name": "win-11.demo.local",
        "host.type": null,
        "inventorySource.type": null,
        "protectionPolicy.name": "Filesystem Backups -TEST PLC",
        "protectionPolicy.type": null,
        "createTime": "2024-11-14T14:34:18.962Z",
        "endTime": "2024-11-14T14:45:31.101Z"
    },
    {
        "category": "PROTECT",
        "classType": "JOB",
        "result.status": "FAILED",
        "result.error.code": "ABA0002",
        "result.error.detailedDescription": "The protection policy backup was unsuccessful because of an agent issue.",
        "result.error.extendedReason": "Protection policy backup was unsuccessful because the Agent failed with the following error: SQLite database initialization failed.",
        "result.error.reason": "Filesystem Backups -TEST PLC: Unable to backup FILE_SYSTEM asset E:\\ on host win-10.demo.local to storage target Filesystem_Backups_-TEST_PLC-ppdm-01-b89b3 because of an agent issue.",
        "result.error.remediation": "Click export log and review the log file to determine the status of the job or check agent logs for more details.",
        "asset.name": "E:\\",
        "asset.type": "FILE_SYSTEM",
        "host.name": "win-10.demo.local",
        "host.type": "APP_HOST",
        "inventorySource.type": null,
        "protectionPolicy.name": "Filesystem Backups -TEST PLC",
        "protectionPolicy.type": "FILE_SYSTEM",
        "createTime": "2024-11-14T14:33:57.609Z",
        "endTime": "2024-11-14T14:45:31.282Z"
    },
    {
        "category": "PROTECT",
        "classType": "JOB",
        "result.status": "FAILED",
        "result.error.code": "ABA0002",
        "result.error.detailedDescription": "The protection policy backup was unsuccessful because of an agent issue.",
        "result.error.extendedReason": "Protection policy backup was unsuccessful because the Agent failed with the following error: SQLite database initialization failed.",
        "result.error.reason": "Filesystem Backups -TEST PLC: Unable to backup FILE_SYSTEM asset C:\\ on host win-11.demo.local to storage target Filesystem_Backups_-TEST_PLC-ppdm-01-b89b3 because of an agent issue.",
        "result.error.remediation": "Click export log and review the log file to determine the status of the job or check agent logs for more details.",
        "asset.name": "C:\\",
        "asset.type": "FILE_SYSTEM",
        "host.name": "win-11.demo.local",
        "host.type": "APP_HOST",
        "inventorySource.type": null,
        "protectionPolicy.name": "Filesystem Backups -TEST PLC",
        "protectionPolicy.type": "FILE_SYSTEM",
        "createTime": "2024-11-14T14:33:58.629Z",
        "endTime": "2024-11-14T14:45:31.619Z"
    },
    {
        "category": "PROTECT",
        "classType": "TASK",
        "result.status": "FAILED",
        "result.error.code": "ABA0002",
        "result.error.detailedDescription": "The protection policy backup was unsuccessful because of an agent issue.",
        "result.error.extendedReason": "Protection policy backup was unsuccessful because the Agent failed with the following error: SQLite database initialization failed.",
        "result.error.reason": "Filesystem Backups -TEST PLC: Unable to backup FILE_SYSTEM asset DISASTER_RECOVERY:\\ on host win-01.demo.local to storage target Filesystem_Backups_-TEST_PLC-ppdm-01-b89b3 because of an agent issue.",
        "result.error.remediation": "Click export log and review the log file to determine the status of the job or check agent logs for more details.",
        "asset.name": "DISASTER_RECOVERY:\\",
        "asset.type": null,
        "host.name": "win-01.demo.local",
        "host.type": null,
        "inventorySource.type": null,
        "protectionPolicy.name": "Filesystem Backups -TEST PLC",
        "protectionPolicy.type": null,
        "createTime": "2024-11-14T14:45:10.680Z",
        "endTime": "2024-11-14T14:56:00.788Z"
    },
    {
        "category": "PROTECT",
        "classType": "TASK",
        "result.status": "FAILED",
        "result.error.code": "ABA0002",
        "result.error.detailedDescription": "The protection policy backup was unsuccessful because of an agent issue.",
        "result.error.extendedReason": "Protection policy backup was unsuccessful because the Agent failed with the following error: SQLite database initialization failed.",
        "result.error.reason": "Filesystem Backups -TEST PLC: Unable to backup FILE_SYSTEM asset DISASTER_RECOVERY:\\ on host win-11.demo.local to storage target Filesystem_Backups_-TEST_PLC-ppdm-01-b89b3 because of an agent issue.",
        "result.error.remediation": "Click export log and review the log file to determine the status of the job or check agent logs for more details.",
        "asset.name": "DISASTER_RECOVERY:\\",
        "asset.type": null,
        "host.name": "win-11.demo.local",
        "host.type": null,
        "inventorySource.type": null,
        "protectionPolicy.name": "Filesystem Backups -TEST PLC",
        "protectionPolicy.type": null,
        "createTime": "2024-11-14T14:45:41.062Z",
        "endTime": "2024-11-14T14:56:30.815Z"
    },
    {
        "category": "PROTECT",
        "classType": "TASK",
        "result.status": "FAILED",
        "result.error.code": "ABA0002",
        "result.error.detailedDescription": "The protection policy backup was unsuccessful because of an agent issue.",
        "result.error.extendedReason": "Protection policy backup was unsuccessful because the Agent failed with the following error: SQLite database initialization failed.",
        "result.error.reason": "Filesystem Backups -TEST PLC: Unable to backup FILE_SYSTEM asset C:\\ on host win-10.demo.local to storage target Filesystem_Backups_-TEST_PLC-ppdm-01-b89b3 because of an agent issue.",
        "result.error.remediation": "Click export log and review the log file to determine the status of the job or check agent logs for more details.",
        "asset.name": "C:\\",
        "asset.type": null,
        "host.name": "win-10.demo.local",
        "host.type": null,
        "inventorySource.type": null,
        "protectionPolicy.name": "Filesystem Backups -TEST PLC",
        "protectionPolicy.type": null,
        "createTime": "2024-11-14T14:45:10.681Z",
        "endTime": "2024-11-14T14:56:00.928Z"
    },
    {
        "category": "PROTECT",
        "classType": "JOB",
        "result.status": "FAILED",
        "result.error.code": "ABA0002",
        "result.error.detailedDescription": "The protection policy backup was unsuccessful because of an agent issue.",
        "result.error.extendedReason": "Protection policy backup was unsuccessful because the Agent failed with the following error: SQLite database initialization failed.",
        "result.error.reason": "Filesystem Backups -TEST PLC: Unable to backup FILE_SYSTEM asset DISASTER_RECOVERY:\\ on host win-01.demo.local to storage target Filesystem_Backups_-TEST_PLC-ppdm-01-b89b3 because of an agent issue.",
        "result.error.remediation": "Click export log and review the log file to determine the status of the job or check agent logs for more details.",
        "asset.name": "DISASTER_RECOVERY:\\",
        "asset.type": "FILE_SYSTEM",
        "host.name": "win-01.demo.local",
        "host.type": "APP_HOST",
        "inventorySource.type": null,
        "protectionPolicy.name": "Filesystem Backups -TEST PLC",
        "protectionPolicy.type": "FILE_SYSTEM",
        "createTime": "2024-11-14T14:33:58.121Z",
        "endTime": "2024-11-14T14:56:01.084Z"
    },
    {
        "category": "PROTECT",
        "classType": "JOB",
        "result.status": "FAILED",
        "result.error.code": "ABA0002",
        "result.error.detailedDescription": "The protection policy backup was unsuccessful because of an agent issue.",
        "result.error.extendedReason": "Protection policy backup was unsuccessful because the Agent failed with the following error: SQLite database initialization failed.",
        "result.error.reason": "Filesystem Backups -TEST PLC: Unable to backup FILE_SYSTEM asset C:\\ on host win-10.demo.local to storage target Filesystem_Backups_-TEST_PLC-ppdm-01-b89b3 because of an agent issue.",
        "result.error.remediation": "Click export log and review the log file to determine the status of the job or check agent logs for more details.",
        "asset.name": "C:\\",
        "asset.type": "FILE_SYSTEM",
        "host.name": "win-10.demo.local",
        "host.type": "APP_HOST",
        "inventorySource.type": null,
        "protectionPolicy.name": "Filesystem Backups -TEST PLC",
        "protectionPolicy.type": "FILE_SYSTEM",
        "createTime": "2024-11-14T14:33:58.287Z",
        "endTime": "2024-11-14T14:56:01.138Z"
    },
    {
        "category": "PROTECT",
        "classType": "JOB",
        "result.status": "FAILED",
        "result.error.code": "ABA0002",
        "result.error.detailedDescription": "The protection policy backup was unsuccessful because of an agent issue.",
        "result.error.extendedReason": "Protection policy backup was unsuccessful because the Agent failed with the following error: SQLite database initialization failed.",
        "result.error.reason": "Filesystem Backups -TEST PLC: Unable to backup FILE_SYSTEM asset DISASTER_RECOVERY:\\ on host win-11.demo.local to storage target Filesystem_Backups_-TEST_PLC-ppdm-01-b89b3 because of an agent issue.",
        "result.error.remediation": "Click export log and review the log file to determine the status of the job or check agent logs for more details.",
        "asset.name": "DISASTER_RECOVERY:\\",
        "asset.type": "FILE_SYSTEM",
        "host.name": "win-11.demo.local",
        "host.type": "APP_HOST",
        "inventorySource.type": null,
        "protectionPolicy.name": "Filesystem Backups -TEST PLC",
        "protectionPolicy.type": "FILE_SYSTEM",
        "createTime": "2024-11-14T14:33:57.950Z",
        "endTime": "2024-11-14T14:56:30.943Z"
    }
]